module.exports = [
    {word:"macho", taboo:["manly","spanish","virile","stud","testosterone"]},
    {word:"blackmail", taboo:["crime","extortion","demand","money","letters"]},
    {word:"blow", taboo:["wind","air","whistle","nose","kiss"]},
    {word:"eggnog", taboo:["christmas","punch bowl","spiked","creamy","brandy"]},
    {word:"ebenezer scrooge", taboo:["christmas carol","character","ghosts","tightwad","humbug!"]},
    {word:"recycle", taboo:["use","bin","waste","cans","paper"]},
    {word:"detective", taboo:["investigate","crime","clues","private eye","sherlock holmes"]},
    {word:"skyscraper", taboo:["empire","tall","new york city","high-rise","building"]},
    {word:"llama", taboo:["south america","alpaca","beast","burden","dalai"]},
    {word:"museum", taboo:["art","paintings","exhibits","buildings","collection"]},
    {word:"eureka!", taboo:["moment","discovery","found","know","revelation"]},
    {word:"lei", taboo:["flowers","necklace","hawaii","greeting","aloha"]},
    {word:"vegan", taboo:["meat","vegetarian","eat","fish","diet"]},
    {word:"flannel", taboo:["shirt","nightgown","cloth","sheets","pajamas"]},
    {word:"wheelbarrow", taboo:["load","gardener","rubbish","handles","carry"]},
    {word:"pez", taboo:["candy","toy","dispenser","push down","collectible"]},
    {word:"fool", taboo:["punk'd","april","idiot","trick","jerk"]},
    {word:"diamond", taboo:["baseball","ring","carats","jewel","engagement"]},
    {word:"trendy", taboo:["faddish","fashionable","stylish","vogue","chic"]},
    {word:"plastered", taboo:["drunk","intoxicated","smashed","walls","ceiling"]},
    {word:"alias", taboo:["fake","name","aka","i.d.","false"]},
    {word:"chip", taboo:["chocolate","cookie","potato","poker","pentium"]},
    {word:"grand slam", taboo:["homer","bases","loaded","4","runs"]},
    {word:"menu", taboo:["restaurant","order","entrees","bill of fare","prices"]},
    {word:"midas touch", taboo:["gold","legend","money","rich","easy"]},
    {word:"bunsen burner", taboo:["heater","lab","experiment","gas","flame"]},
    {word:"funny bone", taboo:["hit","elbom","body","arm","feeling"]},
    {word:"scavenger hunt", taboo:["search","game","find","contest","objects"]},
    {word:"comma", taboo:["punctuation","mark","period","rest","separate"]},
    {word:"pocket", taboo:["watch","hand","pants","trousers","pool table"]},
    {word:"panda", taboo:["bear","black & white","china","bamboo","zoo"]},
    {word:"minutes", taboo:["60","seconds","hours","time","meeting"]},
    {word:"r.s.v.p.", taboo:["invitation","answer","respond","party","coming"]},
    {word:"tiara", taboo:["crown","jeweled","head","gown","miss universe"]},
    {word:"mouthwash", taboo:["rinse","gargle","brush","teeth","breath"]},
    {word:"jackhammer", taboo:["drill","break-up","pavement","construction","rock"]},
    {word:"pentagon", taboo:["5","sides","office building","washington dc","defense"]},
    {word:"flip flops", taboo:["sandals","thongs","toes","beach","politician"]},
    {word:"whisper", taboo:["speak","softly","ear","sound","shout"]},
    {word:"merry-go-round", taboo:["carousel","spin","horses","pole","up & down"]},
    {word:"dark horse", taboo:["unexpected","winner","surprise","behind","chance"]},
    {word:"howdy", taboo:["hi!","hello!","greeting","cowboy","doody"]},
    {word:"big ben", taboo:["london","parliament","chime","clock","time"]},
    {word:"slip", taboo:["pink","fired","freudian","mistake","lingerie"]},
    {word:"canvas", taboo:["tent","sail","cloth","bag","sneakers"]},
    {word:"lie detector", taboo:["test","police","yes","no","polygraph"]},
    {word:"laugh", taboo:["funny","ha-ha","chuckle","giggle","lol"]},
    {word:"spit", taboo:["saliva","rotisserie","drool","expectorate","mouth"]},
    {word:"steeple", taboo:["church","spire","tower","bell","top"]},
    {word:"shower", taboo:["bathroom","bridal","water","clean","april"]},
    {word:"red herring", taboo:["diversion","decoy","curve ball","trick","fake out"]},
    {word:"semi", taboo:["truck","colon","circle","conductor","automatic"]},
    {word:"banjo", taboo:["music","dixieland","bluegrass","strings","strum"]},
    {word:"tooth fairy", taboo:["bed","pillow","money","make believe","night"]},
    {word:"the brothers grim", taboo:["fairy tales","german","siblings","authors","storytellers"]},
    {word:"cough drop", taboo:["lorenge","sore","halls","throat","suck"]},
    {word:"copper", taboo:["penny","pipes","metal","coin","lincoln"]},
    {word:"filling", taboo:["tooth","cavity","dentist","cream","oreo"]},
    {word:"key", taboo:["door","open","car","lock","piano"]},
    {word:"parking meter", taboo:["car","curb","machine","slot","quarters"]},
    {word:"sphinx", taboo:["huge","sculpture","pyramids","man","lion"]},
    {word:"puppet", taboo:["strings","finger","marionette","wooden","pinocchio"]},
    {word:"guru", taboo:["hindu","wise","spiritual","teacher","go-to-guy"]},
    {word:"thomas edison", taboo:["light bulb","electric","inventor","phonograph","movies"]},
    {word:"adult", taboo:["grown-up","mature","old","child","x-rated"]},
    {word:"tie-dye", taboo:["t-shirt","hippie","pattern","psychadelic","colors"]},
    {word:"poison ivy", taboo:["itch","plant","rash","scratch","leaves"]},
    {word:"toll booth", taboo:["highway","pay","attendant","coins","ticket"]},
    {word:"dr. jekyll", taboo:["mr. hyde","robert louis stevenson","split personality","good","evil"]},
    {word:"school bus", taboo:["yellow","children","pick up","vehicle","kids"]},
    {word:"stool pigeon", taboo:["whistle blower","snitch","tattletale","turn in","informer"]},
    {word:"roman colosseum", taboo:["arena","italy","gladiators","nero","thumbs up"]},
    {word:"boa", taboo:["snake","coil","constrictor","feathery","scarf"]},
    {word:"slush", taboo:["snow","rain","weather","fund","puppie"]},
    {word:"wallpaper", taboo:["paste","hang","roll","strip","paint"]},
    {word:"big ten", taboo:["midwest","state","universities","group","compete"]},
    {word:"greeting card", taboo:["hallmark","message","rhyme","occasion","drugstore"]},
    {word:"jet lag", taboo:["air","tired","travel","time","adjust"]},
    {word:"headhunter", taboo:["job","recruiter","find","cannibal","shrunken"]},
    {word:"jingle", taboo:["bells","ring","sleigh","horse","song"]},
    {word:"poker", taboo:["card","hand","texas hold'em","game","bet"]},
    {word:"paul revere", taboo:["ride","warning","british","coming","revolution"]},
    {word:"seagull", taboo:["bird","beach","ocean","wings","landfill"]},
    {word:"gargoyle", taboo:["carved","buildings","grotesque","monsters","ornament"]},
    {word:"octopus", taboo:["tentacles","ocean","arms","8","squid"]},
    {word:"daydream", taboo:["think","sleep","fantasize","bored","mind"]},
    {word:"thong", taboo:["underwear","skimpy","butt","bikini","bathing suit"]},
    {word:"fortune cookie", taboo:["advice","message","chinese","restaurant","predict"]},
    {word:"jacks", taboo:["game pieces","metal","points","rubber ball","pick-up"]},
    {word:"tiffany", taboo:["jewels","store","fifth avenue","breakfast","lamp"]},
    {word:"pupil", taboo:["student","classroom","school","eye","dilated"]},
    {word:"yak", taboo:["ox","tibet","chat","blab","gab"]},
    {word:"lullaby", taboo:["baby","sleep","cradle","sing","rock"]},
    {word:"scale", taboo:["weigh","musical","do re mi","fish","richter"]},
    {word:"bazooka", taboo:["rocket","launcher","war","bubblegum","comics"]},
    {word:"liberty bell", taboo:["ring","crack","freedom","america","symbol"]},
    {word:"cameo", taboo:["jewelry","carved","profile","small","role"]},
    {word:"credit", taboo:["card","money","bank","visa","master"]},
    {word:"gap", taboo:["generation","jeans","old navy","store","mall"]},
    {word:"brown-nose", taboo:["flatter","bootlick","boss","suck-up","yes-man"]},
    {word:"Jogging", taboo:["Morning","Running","Slow","Warm-Up","Exercise"]},
{word:"Flattery", taboo:["Praise","False","Lie","Insincere","Compliment"]},
{word:"All-Rounder", taboo:["Multiple","Talented","Cricketer","Different","Perform"]},
{word:"Senorita", taboo:["Spanish","Women","Song","Word","Title"]},
{word:"Myth", taboo:["False","Belief","Story","Legend","Past"]},
{word:"Spit", taboo:["Liquid","Tobacco","Mouth","Saliva","Content"]},
{word:"Objective", taboo:["Mcq","Aim","Motive","Subjective","Unbiased"]},
{word:"Jaw", taboo:["Bones","Chew","Mouth","Teeth","Upper"]},
{word:"Backbencher", taboo:["Seat","Last","Front","Classroom","Noise"]},
{word:"Winter", taboo:["Cold","Summer","Season","Coming","Temperature"]},
{word:"Karaoke", taboo:["Sing","Along","Words","Drunk","Room"]},
{word:"Starters", taboo:["Variety","Before","Meals","Tikka","Manchurian"]},
{word:"Navel", taboo:["Belly","Stomach","Skin","Abdomen","Hole"]},
{word:"Parcel", taboo:["Courier","Deliver","Package","Collection","Object"]},
{word:"Oil", taboo:["Petrol","Cooking","Sunflower","Saffola","Liquid"]},
{word:"Message", taboo:["Text","Sms","Whatsapp","Instagram","Phone"]},
{word:"Long-Weekend", taboo:["Holiday","Leave","Consecutive","Non-Working","Vacation"]},
{word:"Remake", taboo:["Release","Already","Repeat","Same","Movie"]},
{word:"Toilet", taboo:["Bathroom","Sanitation","Relieve","Leak","Dump"]},
{word:"Television", taboo:["Idiot Box","Serial","Watch","Front","Remote"]},
{word:"Talkative", taboo:["Speak","Much","Lot","Communicate","Chatty"]},
{word:"Single", taboo:["One","Status","Break-Up","Songs","Girlfriend"]},
{word:"Producer", taboo:["Movies","Money","Invests","Film","Example"]},
{word:"Dinner", taboo:["Night ","Meal","Food","Last","Sleep"]},
{word:"Breakup", taboo:["Split","Divide","End","Relationship","Terminate"]},
{word:"Tea", taboo:["Drink","Morning","Cup","Liquid","Break"]},
{word:"Lawn", taboo:["Green","Yard","Grass","Mow","Garden"]},
{word:"Grandmother", taboo:["Father","Ancestor","Family","Elderly","Generation"]},
{word:"Stereotype", taboo:["Generalised","Mistaken","Expectation","View","Simplified"]},
{word:"Villain", taboo:["Bad","Anti-Hero","Mogambo","Gabbar Singh","Mogambo"]},
{word:"Work", taboo:["Pension","Retired","Relax","Office","Holiday"]},
{word:"Samosa", taboo:["Snacks","Aloo","Vegetable","Eatable","Chutney"]},
{word:"Pubg", taboo:["Game","Mobile","Battle","Popular","Multiplayer"]},
{word:"Lunchbox", taboo:["Tiffin","Food","Container","Meals","Break"]},
{word:"Climb", taboo:["Angle","Steep","Mountain","Hill","Stairs"]},
{word:"Gum", taboo:["Teeth","Chew","Food","Fevicol","Adhesive"]},
{word:"Vegetarian", taboo:["Non","Animals","Plants","Kill","Eating"]},
{word:"Disco", taboo:["Dance","Party","Place","Celebrate","Alcohol"]},
{word:"Naachos", taboo:["Crispy","Tasty","Food","Restaurant","Tortilla"]},
{word:"Terrible", taboo:["Disaster","Tragedy","Sad","Victim","Bad"]},
{word:"Puncture", taboo:["Tyre","Air ","Wheel","Deflate","Hole"]},
{word:"Scooter", taboo:["Two-Wheeler","Bike","Motorcycle","Bajaj","Vehicle"]},
{word:"Whiskey", taboo:["Drink","Alcohol","Type","Similar","Party"]},
{word:"Child", taboo:["School","Educate","Teach","Learn","Baby"]},
{word:"Lipstick", taboo:["Red","Face","Woman","Ladies","Apply"]},
{word:"Whisper", taboo:["Speak ","Soft ","Ear","Secret ","Loud"]},
{word:"Soldier", taboo:["Battle","Warrior","War","Attack","Army"]},
{word:"Honey Singh", taboo:["Singer","Girls","Rapper","Brown Rang","High Heels"]},
{word:"Pearl", taboo:["Jewelry","Diver","Oyster","White","Expensive"]},
{word:"Boat", taboo:["Top","Float","Water","Surface","House"]},
{word:"Ayodhya", taboo:["Ram","Babri","Holy","Birthplace","U.P"]},
{word:"Belt", taboo:["Waist","Buckle","Leather","Black","Worn"]},
{word:"Viva", taboo:["Oral ","Face-Face","Teacher","Question","Test"]},
{word:"City", taboo:["Live","Suburb","Outside","Quiet","Town"]},
{word:"Chicken", taboo:["Oil","Fried","Cook","Food","Hen"]},
{word:"Fragile", taboo:["Glass","Careful","Delicate","Broken","Damaged"]},
{word:"Responsibility", taboo:["Ownership","Accountable","Report","Control","Moral"]},
{word:"Wonderful", taboo:["Unbelievable","Marvellous","Amazing","Great ","Fantastic"]},
{word:"Export", taboo:["Product","Import","Foreign","Expensive","Country"]},
{word:"Adult", taboo:["Responsibilities","Mature","Child","Grown Up","Eighteen"]},
{word:"Gabbar Singh", taboo:["Sholay","Basanti","Thakur","Amitabh","Dharmendra"]},
{word:"Vest", taboo:["Banyan","Ganji","Sleeveless","Cloth","Men"]},
{word:"Grave", taboo:["Dig","Funeral","Bury","Cemetery","Dead"]},
{word:"Photoshop", taboo:["Software","Editing","Images","Pictures","Adobe"]},
{word:"Biceps", taboo:["Triceps","Gym","Dumbells","Muscles","Arms"]},
{word:"Cigar", taboo:["Tobacco","Cigarette","Cuban","Smoke","Nicotine"]},
{word:"Johny Lever", taboo:["Comedy","Bollywood","Actor","Stand-Up","Funny"]},
{word:"Thanks", taboo:["Welcome","Appreciate","Gratitude","Grateful","Express"]},
{word:"Nun", taboo:["Priest","Sister","Catholic","Woman","Convent"]},
{word:"Celebrity", taboo:["Stars","Recognised ","Media","Famous","Actor"]},
{word:"Flamboyant", taboo:["Stylish","Cool","Confident","Lively","Impressive"]},
{word:"Intelligent", taboo:["Smart","Quick","Fast","Marks","First"]},
{word:"Constipated", taboo:["Morning","Bowel","Toilet","Tough","Difficult"]},
{word:"Horror", taboo:["Frighten","Fear","Movie","Genre","Scary"]},
{word:"Jugs", taboo:["Jar","Container ","Big ","Rack ","Liquid"]},
{word:"Cooperate", taboo:["Unite","Help","Together","Everyone","Support"]},
{word:"Ridiculous", taboo:["Stupid","Unbelievable","Senseless","Absurd","Foolish"]},
{word:"Blink", taboo:["Eye ","Wink","See","Look","Open"]},
{word:"Syrup", taboo:["Maple","Butter","Pancakes","Sweet","Liquid"]},
{word:"Grass", taboo:["Green","Garden","Walk","Park","Plant"]},
{word:"Couple", taboo:["Two","Relationship","Together","Married","Combine"]},
{word:"Tavern", taboo:["Drink","Whiskey","Alcohol","People","Place"]},
{word:"People", taboo:["Street","Crowd","Many","Herd","Humans"]},
{word:"Peacock", taboo:["Dance","Rains","Colourful","Bird","Plumage"]},
{word:"Jeans", taboo:["Levis","Denim","Wrangler","Wear","Legs"]},
{word:"Survey", taboo:["Opinion","Fill Out","Ask","Questions","Examine"]},
{word:"Lehenga", taboo:["Marriage","Special","Dress","Girls","Women"]},
{word:"Ankle", taboo:["Foot","Break","Sprain","Leg","Knee"]},
{word:"Full House", taboo:["Tickets","Occupied","Availaible","Seat","Filled"]},
{word:"Drought", taboo:["Desert","Rain","Water","Dry","Fail"]},
{word:"Breakfast", taboo:["Morning","Meal","Food","Dishes","Time"]},
{word:"Nail", taboo:["Tool","Hammer","Swing","Build","Cut"]},
{word:"Boss", taboo:["Manager","Senior","Relationship","Report","Top"]},
{word:"Fantasy", taboo:["Imagination","Think","Impossible","Believe","League"]},
{word:"Party", taboo:["Fun","Friday ","Dance","Music","Enjoy"]},
{word:"Goggles", taboo:["Sunglassses","Glares","Eyewear","Equipment","Enclose"]},
{word:"Pollution", taboo:["Delhi","Air ","Quality","Harmful","Poisionous"]},
{word:"Traffic", taboo:["Vehicles","Road","Cars","Population","Transport"]},
{word:"Bed", taboo:["Clothes","Pajamas","Night","Sleepover","Mattress"]},
{word:"Necklace", taboo:["Women","Worn","Expensive","Body","Lady"]},
{word:"Doctor", taboo:["Ambulance","Patient","Hospital","Sick","Person"]},
{word:"Snake", taboo:["Slithers","Black","Reptile","Crawls","Type"]},
{word:"Joystick", taboo:["Arcade","Atari","Airplane ","Computer ","Happy"]},
{word:"Gray", taboo:["Ride","Donkey","Cart","Stubborn","Shade"]},
{word:"Barber", taboo:["Hairdresser","Salon","Cut","Person","Hair"]},
{word:"Thug", taboo:["Violent ","Criminal","Gang","Robber","Swindler"]},
{word:"Lottery", taboo:["Gambling","Lucky","Money","Ticket","Win"]},
{word:"Whatsapp", taboo:["Chat","Message","Friends","Family","App"]},
{word:"Taxes", taboo:["Money","Salary","Deduct","Government","Income"]},
{word:"Prisoner", taboo:["Guard","Crime","Punish","Criminal","Jail"]},
{word:"Devdas", taboo:["Shahrukh","Aishwarya","Character","Bhansali","Movie"]},
{word:"Exam", taboo:["Test","Marks","Board","Pass","Clear"]},
{word:"Election", taboo:["Leader","Vote","Democracy","National","Government"]},
{word:"Shopping", taboo:["Buy","E-Commerce","Purchase","Clothes","Electronics"]},
{word:"Appraisal", taboo:["Salary","Increment","Income","Raise","Hike"]},
{word:"Cliffhanger", taboo:["Tense","Exciting","Movie","Ending","Situation"]},
{word:"Veteran", taboo:["Old","Experienced","Knows","Elder ","Person"]},
{word:"Road-Trip", taboo:["Holiday","Vacation","Drive","Vehicle","Journey"]},
{word:"Prank", taboo:["Joke ","Surprise ","Hidden ","Punk ","Trick"]},
{word:"Anxious", taboo:["Nervous","Afraid","Fear","Worried","Uneasy"]},
{word:"Paparazzi", taboo:["Media","Photographers","Celebrity","Pictures","Follow"]},
{word:"Charger", taboo:["Mobile","Electricity","Battery","Switch","Adaptor"]},
{word:"Chart", taboo:["Visual","Data","Graph","Numbers","Excel"]},
{word:"Elephant", taboo:["Animal","Huge","Trunk","Ivory","Teeth"]},
{word:"Deer", taboo:["Animal","Hunt","Gun","Woods","Forest"]},
{word:"House", taboo:["Expensive","Mansion","Home","Live","Place"]},
{word:"Surgeon", taboo:["Operation","Hospital","Doctor","Surgery","Patient"]},
{word:"Intoxicant", taboo:["Drugs","Type","Psychedelic","Harmful","Drinks"]},
{word:"Boyfriend", taboo:["Partner","Couple","Girl","Male ","Relationship"]},
{word:"Engineer", taboo:["Non-Medical","Btech","Stream","Profession","Branch"]},
{word:"Hair", taboo:["Shave","Body","Beard","Head","Bald"]},
{word:"Swimming", taboo:["Water","Strokes","Pool","Float","Phelps"]},
{word:"Sale", taboo:["Discount","Festive","Lowered","Price","Reduced"]},
{word:"Delivery", taboo:["Give","Food","Package","Reach","Buy"]},
{word:"Downpour", taboo:["Rain","Torrent","Heavy","Thunderstorm","Flood"]},
{word:"Pillow", taboo:["Head","Sleep","Support","Bed","Rest"]},
{word:"Jail", taboo:["Handcuffs","Arrest","Criminal","Police","Prisoner"]},
{word:"Handkerchief", taboo:["Pocket","Sweat","Hands","Inside","Cloth"]},
{word:"Brunch", taboo:["Combine","Meals","Together","Food","Mixture"]},
{word:"Mix", taboo:["Blend","Stir","Mingle ","Combine ","Drink"]},
{word:"Miser", taboo:["Money","Stingy","Cheap","Spend","Little"]},
{word:"Fusion", taboo:["Mixture","Classical","Nuclear","Music","Song"]},
{word:"Cake", taboo:["Cut","Chocolate","Birthday","Bake","Celebrate"]},
{word:"Funnel", taboo:["Chug","Frat","Oil ","Tube ","Beer"]},
{word:"Lion", taboo:["King","Jungle","Simba","Animal","Wild"]},
{word:"Engaged", taboo:["Committed","Busy","Marriage","Ring","Occupied"]},
{word:"Duplicate", taboo:["Shahrukh","Same","Similar","Identical","Double"]},
{word:"Click", taboo:["Tap","Noise","Mouse","Select","Connect"]},
{word:"Giant", taboo:["Massive","Dinosaur","Large","Big","Huge"]},
{word:"Politician", taboo:["Scandal","Corruption","Bribe","Government","Leader"]},
{word:"Buffalo", taboo:["Milk","Cow","Animal","Four","Oxen"]},
{word:"Trolley", taboo:["Airport","Luggage","Stuff","Baggage","Wheels"]},
{word:"Slipper", taboo:["Feet","Chappal","Hawai","Sandal","Bata"]},
{word:"Rooster", taboo:["Chicken","Cock","Crow ","Male ","Hen"]},
{word:"Rugby", taboo:["Newzealand","Run","Rough","Blood","Australia"]},
{word:"Mushroom", taboo:["Fungus","Sauce","White","Eat","Plant"]},
{word:"Cameo", taboo:["Guest","Small","Movie","Brief","Minor"]},
{word:"Mobile", taboo:["Smartphone","Call","Device","Connect","Talk"]},
{word:"Hardwork", taboo:["Sincere","Study","Long ","Success","Poor"]},
{word:"Gag ", taboo:["Trick","Ball","Throat","Joke ","Choke"]},
{word:"Vodka", taboo:["Alcohol","Beer","Russian","Drink","Beverage"]},
{word:"Fishing", taboo:["Bait","Hook","Water","Sea ","Ocean"]},
{word:"Resign", taboo:["Leave","Quit","Job","Papers","Work"]},
{word:"Polite", taboo:["Manners","Friendly","Nice","Smile","Soft"]},
{word:"Mermaid", taboo:["Ariel","Sea","Aquatic","Imaginary","Fictional"]},
{word:"Cunning", taboo:["Deceit","Evasive","Smart","Skilled","Benefit"]},
{word:"Soup", taboo:["Tomato","Manchurian","Sweet Corn","Drink","Liquid"]},
{word:"Meeting", taboo:["Schedule","Together","Talk","Gathering","Discuss"]},
{word:"Barefoot", taboo:["Summer","Beach","Shoes","Socks","Slippers"]},
{word:"Student", taboo:["School","Pupil","Kid","Young","Age"]},
{word:"Guitar", taboo:["Rockstar","Instrument","Music","Shape","Girls"]},
{word:"Appreciate", taboo:["Praise","Grateful","Value","Recognize","Reward"]},
{word:"Sky", taboo:["Blue","Clouds","Birds","Sun","Above"]},
{word:"Flood", taboo:["Water","Rain","Monsoon","Year","River"]},
{word:"Gym", taboo:["Exercise","Workout","Weight","Train","Body"]},
{word:"Firefighter", taboo:["House","Flames","Person","Emergency","Burning"]},
{word:"Athlete", taboo:["Runner","Sportsman","Competes","Participates","Champion"]},
{word:"Spade", taboo:["Tool","Soil","Dig","Hole","Object"]},
{word:"Blanket", taboo:["Cold ","Cover","Warm","Quilt","Heat"]},
{word:"Fever", taboo:["Sick","Ill","Temperature","Unwell","Thermometer"]},
{word:"Explode", taboo:["Blast","Implode","Bomb","Destroy","Burst"]},
{word:"Palindrome", taboo:["Malyalam","Word  ","Spells","Forward","Both"]},
{word:"Twice", taboo:["Amount","Double","Number","Triple","Two"]},
{word:"Internship", taboo:["Job","College","Full-Time","Part-Time","Temporary"]},
{word:"Lunch", taboo:["Meal","Afternoon","Food","Eat","Home"]},
{word:"Dessert", taboo:["Cake","Sweet","Meal ","Dinner","Food"]},
{word:"Goa", taboo:["Party","Vacation","Holiday","Destination","Bachelors"]},
{word:"Mogambo", taboo:["Amrish Puri","Villain","Anil Kapoor","Mr. India","Hawa Hawai"]},
{word:"Bulldozer", taboo:["Demolish","Destruction","Construction","Machine","Move"]},
{word:"Walk", taboo:["Backpack","Hike","Woods","Mountain","Cab"]},
{word:"Sky", taboo:["Blue","Outside","Sun","Over","Above"]},
{word:"Topper", taboo:["First","Best","Highest","Studious","Sincere"]},
{word:"Comedy", taboo:["Laugh","Funny","Humorous","Joke ","Act"]},
{word:"Mascara", taboo:["Eyelashes","Enhance","Women","Ladies","Cosmetic"]},
{word:"Jacuzzi", taboo:["Tub ","Hot ","Bubble","Jets ","Spa"]},
{word:"Ice-Cream", taboo:["Baskin Robins","Naturals","Hagen Dazs","Softy","Cone"]},
{word:"Recess", taboo:["Break","Children","Students","Free","Lunch"]},
{word:"Doubt", taboo:["Unsure","Uncertain","Confidence","Hesitate","Question"]},
{word:"Detox", taboo:["Cleanse","Purify","Body","Remove","Toxins"]},
{word:"Sherwani", taboo:["Men","Traditional","Dress","Kurta","Fancy"]},
{word:"Savage", taboo:["Uncivilised","Brutal","Violent","Fierce","Vicious"]},
{word:"Maximum", taboo:["Amount","Minimum","Lowest","Wage","Largest"]},
{word:"Echo", taboo:["Repeat","Sound","Noise","Reflection","Audio"]},
{word:"Mercedes", taboo:["Car","Lamborghini","Automobile","Vehicle","Bmw"]},
{word:"Ink", taboo:["Tatoo","Prison","Pen ","Needle ","Draw"]},
{word:"Wine", taboo:["Grape","White","Red ","Alcohol","Romantic"]},
{word:"Bread", taboo:["Jam","Toast","Butter","Breakfast","Eat "]},
{word:"Immortal", taboo:["Die ","Live ","Forever ","Eternity","Youth"]},
{word:"Hr", taboo:["Department","Resume","Cv","Recruitment","Hiring"]},
{word:"Ship", taboo:["Wind","Sail","Boat","Ocean","Anchor"]},
{word:"Soap", taboo:["Water","Clean","Daily","Bath","Type"]},
{word:"Biopic", taboo:["Type","Examples","Genre","History","Biography"]},
{word:"Bear", taboo:["Wood","Brown","Black","Animal","Honey"]},
{word:"Corporate", taboo:["Mnc","Company","Culture","Organisation","Large"]},
{word:"Distributor", taboo:["Agent","Supplier","Owner","Shop","Businessman"]},
{word:"Snow", taboo:["Storm","Blizzard","Cold","Weather","Ice"]},
{word:"Storm", taboo:["Hurricane","Tornado","Wind","Damage","Violent"]},
{word:"Facebook", taboo:["Social","Friends","Website","Company ","Family"]},
{word:"Grill", taboo:["Fire","Meat","Barbecue","Cook","Question"]},
{word:"Probe", taboo:["Alien","Abducted","Examine","Penetrate","Interrogate"]},
{word:"Bartender", taboo:["Cocktail","Mix ","Pour ","Alcohol","Serve"]},
{word:"Sacred", taboo:["Blessed","Worship","Holy","Religious","God"]},
{word:"Brownie", taboo:["Hash","Chocolate","Sweet ","Baked","Dessert"]},
{word:"Clinic", taboo:["Doctor","Patient","Healthcare","Facility","Private"]},
{word:"Rapper", taboo:["Hip-Hop","Eminem","Rhyme","Music","Sing"]},
{word:"Projector", taboo:["Display","Screen","Show","Large","Different"]},
{word:"Inspire", taboo:["Motivate","Uplfit","Hope","Urge","Push"]},
{word:"Emraan Hashmi", taboo:["Kiss","Actor","Male","Movie","Hero"]},
{word:"Guilty ", taboo:["Innocent","Pleasure","Wrong","Sorry","Criminal"]},
{word:"Topper", taboo:["First","Studious","Intelligent","Class","Person"]},
{word:"Exotic", taboo:["Unusual","Strange","Animal","Island","Exciting"]},
{word:"Item-Song", taboo:["Katrina Kaif","Dance","Actress","Chikni Chameli","Malaika"]},
{word:"Teacher", taboo:["Maam","Women","Strict","Person","Profession"]},
{word:"Filmfare", taboo:["Award","Movie","Function","Actors","Bollywood"]},
{word:"Fair", taboo:["Dark","White","Light","Blonde","Colour"]},
{word:"Disease", taboo:["Condition","Unwell","Fever","Infection","Sick"]},
{word:"Sequel", taboo:["Continues","Version","Film","New","Next"]},
{word:"Meme", taboo:["Funny","Image","Joke","Online","Photo"]},
{word:"Insomnia", taboo:["Sleep","Toss","Restless","Bed ","Night"]},
{word:"Inchitape", taboo:["Length","Measurement","Height","Tailor","Stich"]},
{word:"Socks", taboo:["Shoes","Pair","Feet","Dobby","Cloth"]},
{word:"Landlord", taboo:["Owner","Rent","House","Apartment","Flat"]},
{word:"Marriage", taboo:["Arrange","Love","Divorce","Individuals","People"]},
{word:"Newspaper", taboo:["Morning","Tea","Digital","Read","Educated"]},
{word:"Bracelet", taboo:["Wrist","Jewelery","Hands","Arm","Band"]},
{word:"Speed Dating", taboo:["Fast ","Singles","Tables","Many ","Time"]},
{word:"Google", taboo:["Search","Gmail","Company","Tech","Maps"]},
{word:"Accident", taboo:["Road","Collision","Crash","Cars","Vehicles"]},
{word:"Sneeze", taboo:["Season","Allergy","Itch","Spring","Remember"]},
{word:"Ritual", taboo:["Daily","Repeat","Tradition","Ceremony","Habit"]},
{word:"Invasion", taboo:["Forcefully","Country","Intrusion","Army","Military"]},
{word:"Independence", taboo:["Freedom","1947","15Th August","Control","Self-Government"]},
{word:"King", taboo:["Ruler","Supreme","Leader","Person","Monarch"]},
{word:"Battle", taboo:["War","Panipat","Solider","Army","Fight"]},
{word:"Gunpowder", taboo:["Mixture","Explosive","Substance","Firearms","Fireworks"]},
{word:"Edict", taboo:["Proclamation","Law","Decree","Writing","Kings"]},
{word:"Slavery", taboo:["Blacks","Abolished","Owns","Property","Bondage"]},
{word:"Tipu Sultan", taboo:["Mysore","British","Karnataka","Ruler","Seringapatnam"]},
{word:"Akbar", taboo:["Great","Mughal","Jodha Bai","Din-I-Llahi","Salim"]},
{word:"Rani Of Jhansi", taboo:["1857","Queen","British","Woman","Fought"]},
{word:"Nationalism", taboo:["Ideology","Sovereignity","Homeland","Liberalism","Communism"]},
{word:"Mahatma Gandhi", taboo:["Freedom","Independence","Non-Violence","Godse","Leader"]},
{word:"Indus Valley", taboo:["Civilisation","First","Drainage","Planned","India"]},
{word:"Buddhism", taboo:["Religion","Gautam","Monks","Jainism","Hinduism"]},
{word:"Mughals", taboo:["Babur","Akbar","Shah Jahan","Jahangir","Aurangzeb"]},
{word:"Revolt", taboo:["1857","Violent","Uprising","Change","System"]},
{word:"Partition", taboo:["Country","Pakistan","India","Division","Split"]},
{word:"Fort", taboo:["Red Fort","Monument","Protect","Royal","Magnificent"]},
{word:"Vedas", taboo:["Ancient ","Religious","Books","Scripture","Texts"]},
{word:"Nawab", taboo:["Title","Mughal","Bengal","Awadh","Administrator"]},
{word:"Coronation", taboo:["Ceremony","Crown","Custom","Event","Kings"]},
{word:"Panipat", taboo:["Battle","Haryana","British","Place","Three"]},
{word:"Marathas", taboo:["Maharashtra","Group","Battle","Mughals","Shivaji"]},
{word:"Subhash Chandra Bose", taboo:["Freedom Fighter","Ina","Bengal","Congress","Nehru"]},
{word:"Jizziya", taboo:["Tax","Non-Muslim","Aurangzeb","Pay","Controversy"]},
{word:"Maharana Pratap", taboo:["Ruler","Akbar","Mewar","King","Bravery"]},
{word:"Democracy", taboo:["System","Vote","Government","Elect","India"]},
{word:"Civilisation", taboo:["Greek ","Indus","Society","French","British"]},
{word:"Taxila", taboo:["Learning","University","Education","Ancient","Place"]},
{word:"Chauri Chaura", taboo:["Non-Cooperation","Burnt","Police","Gandhi","Place"]},
{word:"Kohinoor", taboo:["Diamond","British","Stole","Valuable","Famous"]},
{word:"Chanakya", taboo:["Mauryan","Chandragupta","Strategy","Kingmaker","Amit Shah"]},
{word:"Jagir", taboo:["Land","Mughal","Grant","Piece","Maintain"]},
{word:"Nazi", taboo:["Germany","Jews","Hitler","Genocide","Holocaust"]},
{word:"Royal", taboo:["Origin","King","Lavish","Grand","Monarch"]},
{word:"Nizam", taboo:["Royal","Hyderabad","Title","Term","Mughal"]},
{word:"Annexation", taboo:["Control","Force","Crimea","Country","Territory"]},
{word:"Kingdom", taboo:["Land","Monarch","Control","Area","Rule"]},
{word:"Non-Cooperation", taboo:["Gandhi","British","Non-Violence","Protest","Defy"]},
{word:"Babarnama", taboo:["Book","Mughal","First","Conquests","Administration"]},
{word:"Palace", taboo:["Building","Reside","Stay","Royal","House"]},
{word:"Throne", taboo:["King","Ruler","Sit","Leader","Seat"]},
{word:"Tomb", taboo:["Buried","Rulers","Enclosure","Monument","Structure"]},
{word:"Stupa", taboo:["Buddhism","Sanchi","Architecture","Ancient","Monument"]},
{word:"Aryabhatta", taboo:["Zero","Mathematician","Astronomer","Ancient","Genius"]},
{word:"Ajanta", taboo:["Maharashtra","Caves","Tourist","Scultpors","Buddhist"]},
{word:"Ancient", taboo:["Earlier","Classical","Antique","Vintage","Retro"]},
{word:"Secular", taboo:["Religion","Violence","Official","Practice","Ideology"]},
{word:"Courtier", taboo:["Administrator","Person","King","Ruler","Advisor"]},
{word:"Birbal", taboo:["Akbar","Jokes","Intelligent","Mughal","Stories"]},
{word:"Washington", taboo:["Amercian","Us","President","First","Leader"]},
{word:"Pottery", taboo:["Mud","Clay","Process","Method","Vessels"]},
{word:"Sword", taboo:["Weapon","Blade","Knife","Object","Sharp"]},
{word:"Cavalry", taboo:["Horse","Warriors","Infantry","Soliders","Fight"]},
{word:"Insignia", taboo:["Symbol","Flag","Sign","Mark","Power"]},
{word:"Museum", taboo:["Artifacts","Old","Ancient","Objects","Place"]},
{word:"Bc", taboo:["Ad","Before Christ","First","Dates","Events"]},
{word:"1857", taboo:["Year","Revolt","Independence","Freedom ","War"]},
{word:"Renaissance", taboo:["Enlightenment","Reform","Awakening","European","Art"]},
{word:"Harappa", taboo:["Indus","Civilisation","Mohenjodaro","Place","Site"]},
{word:"Tradition", taboo:["Past","Similar","Rules","Method","Generations"]},
{word:"Dinosaur", taboo:["Jurassic","Godzila","T-Rex","Reptiles","Large"]},
{word:"Dynasty", taboo:["Lineage","Hereditary","Succession","Same","Family"]},
{word:"Folklore", taboo:["Story","Legend","Beliefs","Myths","Traditions"]},
{word:"Conquer", taboo:["Invade","Attack","Occupy","Control","Military"]},
{word:"Stone-Age", taboo:["Early","Ancient","Pre-Historic","Period","Time"]},
{word:"Neanderthal", taboo:["Human","Species","Closest","Man","Homo Sapiens"]},
{word:"Reform", taboo:["Change","Awaken","Improve","Better","Social"]},
{word:"Nation", taboo:["State","Country","Borders","Land","Area"]},
{word:"Pyramid", taboo:["Egypt","Wonder","Conical","Structure","Traingular"]},
{word:"Alexander", taboo:["Great","Porus","Sikander","Greek","Conquer"]},
{word:"Greece", taboo:["Mythology","Civilisation","Democracy","Olympics","Country"]},
{word:"Cave", taboo:["Lion","Forest","Early","Jungle","Inhabit"]},
{word:"Mahabharat", taboo:["Characters","Part","Associated","Pandavas","Kauravas"]},
{word:"Aryan", taboo:["Invasion","Dravidian","North","Migrate","Descendant"]},
{word:"Port", taboo:["Sea","Trade","Place","Area","Ships"]},
{word:"Ashoka", taboo:["Maurya","Kalinga","Buddhist","Chandragupta","Emperor"]},
{word:"Guptas", taboo:["Dynasty","Golden","Famous","Hindu","Samudragupta"]},
{word:"Jataka", taboo:["Buddhist","Tales","Storires","Life","Morals"]},
{word:"Pataliputra", taboo:["Gupta","Magadh","Ancient","Nanda","Patna"]},
{word:"Kalidasa", taboo:["Poet","Plays","Shakuntala","Meghdoot","Gupta"]},
{word:"Ambassador", taboo:["Dignitary","Representative","Envoy","Diplomat","Country"]},
{word:"Coins", taboo:["Currency","Rupee","Money","Round","Metal"]},
{word:"Nalanda", taboo:["University","Learning","Famous","Buddhist","Centre"]},
{word:"Cholas", taboo:["South","Rulers","Dynasty","Tamil","Temples"]},
{word:"Sanskrit", taboo:["Language","Brahmanical","Oldest","Mother","Elite"]},
{word:"Razia Sultana", taboo:["Female","Delhi","Sultanate","Ruler","13Th Century"]},
{word:"Caste", taboo:["Occupation","Surname","Birth","Varnas","System"]},
{word:"Sufi", taboo:["Saint","Islam","Wanderers","Sing","Mystic"]},
{word:"Napolean", taboo:["Bonaparte","French","Little","Ruler","King"]},
{word:"Communism", taboo:["Ideology","Marx","China ","Soviet","System"]},
{word:"Gold", taboo:["Metal ","Precious","Jewellry","Valuable","Coin"]},
{word:"British", taboo:["English","Rulers","People","Nationality","Foreign"]},
{word:"Copper", taboo:["Metal ","Prehistoric","Electricity","Bronze","Wires"]},
{word:"Mural", taboo:["Wall","Painting","Form","Art","Ceiling"]},
{word:"Sati", taboo:["Custom","Evil","Pyre","Women","Burnt"]},
{word:"Migration", taboo:["Move","Settle","Travel","Shift","Transport"]},
{word:"Rajput", taboo:["Caste","Warrior","Rajasthan","Martial","Community"]},
{word:"Assasinate", taboo:["Kill","Murder","End","Premature","Finish"]},
{word:"Dandi", taboo:["Salt","Gandhi","March","Place","Gujarat"]},
{word:"Versailles", taboo:["Treaty","War","End","Peace","Location"]},
{word:"Laws", taboo:["Rules","Govern","Order","Regulate","Punish"]},
{word:"Feminism", taboo:["Ideology","Women","Equality","West","Thought"]},
{word:"Kathak", taboo:["Dance","Classical","North","Storyteller","Form"]},
{word:"Discrimination", taboo:["Apartheid","Segregation","Different","Mistreat","Treatment"]},
{word:"Khadi", taboo:["Gandhi","Cloth","Textile","Dress","British"]},
{word:"Archery", taboo:["Arjuna","Concentration","Ram","Bow","Arrow"]},
{word:"Gurukul", taboo:["Study","Small","Young","Ashram","Place"]},
{word:"Heir", taboo:["Successor","Prince","King","Throne","Son"]},
{word:"Peace", taboo:["War","Quiet","White ","Conflict","Treaty"]},
{word:"Zamindar", taboo:["Landlord","Ownership","System","British","Rich"]},
{word:"Bhagat Singh", taboo:["Punjab","Revolutionary","Assasinate","Saunders","Legend"]},
{word:"Swadeshi", taboo:["Indian","Movement","Foreign","National ","Home"]},
{word:"Satyagraha", taboo:["Gandhi","Non-Violence","Ahimsa","Truth","Freedom"]},
{word:"Holocaust", taboo:["Hitler","Jews","World War Ii","Killed","Massacre"]},
{word:"Mangal Pandey", taboo:["1857","Sepoy","Aamir","Movie","Revolt"]},
{word:"Dr. Ambedkar", taboo:["Oppressed","Constitution","Scheduled","Freedom ","Caste"]},
{word:"Viceroy", taboo:["Irwin","Mountbatten","Governor","British","Country"]},
{word:"Exile", taboo:["Banish","Throw","Expel","Disallow","Threat"]},
{word:"Parsi", taboo:["Religion","Iran","Tata","Minority","Mumbai"]},
{word:"Silk Road", taboo:["Route","Trade","China ","Network","Connect"]},
{word:"Yoga", taboo:["Meditation","Pose","Exercise","Breathing","Spiritual"]},
{word:"Spiritual", taboo:["Religion","Calm","Meditate","Soul","God"]},
{word:"Namaste", taboo:["Greeting","Indian","Hands","Hello","Type"]},
{word:"Mirabai", taboo:["Krishan","Devotee","Dedicated","Poet","Bhakti"]},
{word:"Cow", taboo:["Holy","Animal","Beef","Worship","Hindu"]},
{word:"Columbus", taboo:["Discovery","America","Christopher","Explorer","Voyage"]},
{word:"Kurukshetra", taboo:["Battle","Pandavas","Kauravas","Mahabharat","Haryana"]},
{word:"Bharatnatyam", taboo:["Dance","Classical","Tamil Nadu","Indian","Art"]},
{word:"Konark", taboo:["Orissa","Puri","Sun","Temple","Worship"]},
{word:"Accupressure", taboo:["Needles","Hands","Feet","Pressure","Medicine"]},
{word:"Kalarippayattu", taboo:["Martial","Tamil Nadu","Fighting","Ancient","Gatka"]},
{word:"Ayuerveda", taboo:["Homepathy","Allopathy","Medicine","Herbal","Natural"]},
{word:"Kung-Fu", taboo:["Martial","Chinese","Fight ","Panda ","Karate"]},
{word:"Tribals", taboo:["Remote","Secluded","Indigenous","Forest","Adivasi"]},
{word:"Treasure", taboo:["Gold","Money","Riches","Hunt","Quest"]},
{word:"Handicrafts", taboo:["Handmade","Item","Object","Simple","Hands"]},
{word:"Varanasi", taboo:["Benaras","Ganga","Ghat","Town","Holy"]},
{word:"Kumbh", taboo:["Mela","Allahabad","Twelve","Ganga","Sadhus"]},
{word:"Conspiracy", taboo:["Betray","Plan","Plot","Murder","Scheme"]},
{word:"Invasion", taboo:["Attack","Conquer","Subjucate","Ruler","Plunder"]},
{word:"Brahmacharya", taboo:["Virgin","Monastic","Celibacy","Sex","Contact"]},
{word:"Monastery", taboo:["Monks","Buddhism","Place","Stay","Reside"]},
{word:"Sacrifice", taboo:["Offer","Kill","Slaughter","Surrender","Give-Up"]},
{word:"Yajna", taboo:["Ritual","Devotion","Worship","Fire","Hinduism"]},
{word:"Aurangzeb", taboo:["Mughal","Religious","Akbar","Jahangir","Sharia"]},
{word:"Chariot", taboo:["Wheels","Krishna","Carriage","Horses","Transport"]},
{word:"Madurai", taboo:["Tamil","South","Temple","Meenakshi","Ancient"]},
{word:"Honour", taboo:["Respect","Esteem","King","Fulfill","Salute"]},
{word:"Flag", taboo:["Symbol","Army","King","Fabric","Cloth"]},
{word:"Manuscript", taboo:["Book","Document","Hand","Typed","Printed"]},
{word:"Barter", taboo:["Exchange","Goods","Money","Trade","Ancient"]},
{word:"Persia", taboo:["Iran","Nuclear","Empire","Shia","Asia"]},
{word:"Empire", taboo:["Rule","King","Control","Country","Large"]},
{word:"Tansen", taboo:["Akbar","Singer","Rain","Classical","Music"]},
{word:"Divine", taboo:["God","Spiritual","Rapper","Supreme","Supernatural"]},
{word:"Sandstone", taboo:["Material","Red Fort","Construction","Bulding","Soft"]},
{word:"Stepwell", taboo:["Steps","Descend","Water","Pond","Climb"]},
{word:"Khajuraho", taboo:["Mp","Erotic","Sculptures","Heritage","Temples"]},
{word:"Jerusalem", taboo:["Isreal","Jews","Christian","Muslim","Holy"]},
{word:"Pillar", taboo:["Stone","Ceiling","Roof","Support","Cylinder"]},
{word:"Ghazni", taboo:["Invader","Attacked","India","Plundered","Mahmud"]},
{word:"Kalinga", taboo:["Battle","Ashoka","Orissa","Buddhism","Maurya"]},
{word:"Vasco Da Gama", taboo:["Goa","Portugese","Explorer","Sea","Calicut"]},
{word:"Mountbatten", taboo:["Independence","1947","Governor","Viceroy","Nehru"]},
{word:"Peshwa", taboo:["Maratha","Minister","Bajirao","Family","Shivaji"]},
{word:"Telegraph", taboo:["Messages","Communication","Device","Code","Transmit"]},
{word:"Ghadar", taboo:["Revolutionary","British","Punjab","Party","Rebellion"]},
{word:"Swaraj", taboo:["Self","Governance","Rule","Total","Tilak"]},
{word:"Mongols", taboo:["Invaders","Chengiz","Largest","Empire","Fierce"]},
{word:"Lincoln", taboo:["President","Slavery","Second","Abraham","Us"]},
{word:"Sher Shah", taboo:["Suri","Humayun","Rupee","Sasaram","Mughal"]},
{word:"Kabir", taboo:["Doha","Saint","Poet","Bhakti","Sayings"]},
{word:"Charter", taboo:["Document","Principles","Statement","Rights","Un"]},
{word:"Shivaji", taboo:["Chatrapati","Maratha","Maharashtra","Mughals","Aurangzeb"]},
{word:"Dharma", taboo:["Religion","Principles","Duty","Behaviour","Law"]},
{word:"Dominion", taboo:["Independent","Semi","Canada","British","Countries"]},
{word:"Govern", taboo:["Rule","Police","Administer","Run","Conduct"]},
{word:"Era", taboo:["Time","Period","Duration","Long","Span"]},
{word:"Industrialisation", taboo:["Machines","Factory","Workers","Manufcaturing","Agrarian"]},
{word:"Capitalism", taboo:["Workers","Ownership","Merit","System","Private"]},
{word:"Compass", taboo:["Route","Sea","Magnetic","Sailors","Navigation"]},
{word:"Diversity", taboo:["Different","Multiple","Range","Unity","Variety"]},
{word:"Trigonometry", taboo:["Mathematics","Sine","Cos ","Tan","Angle"]},
{word:"Explorer", taboo:["Vasco","Columbus","Voyage","Adventure","Sea "]},
{word:"Ship", taboo:["Vessel","Sea","Ocean","Transport","Waterways"]},
{word:"Territory", taboo:["Land","Area","Region","Piece","Division"]},
{word:"Mummy", taboo:["Egypt","Preserved","Dead","Person","Human"]},
{word:"Indigo", taboo:["Cultivation","Revolt","Rebellion","Peasant","Farmers"]},
{word:"Lumbini", taboo:["Birthplace","Buddha","Gautama","Siddhartha","Nepal"]},
{word:"Julius Ceasar", taboo:["Roman","Brutus","Shakespeare","Assasinated","General"]},
{word:"Refugee", taboo:["Persecuted","Partition","Escape","Leave","Country"]},
{word:"Downfall", taboo:["Rise","End","Finish","Loss","Destruction"]},
{word:"Troy", taboo:["Helen","Sparta","Greek","Trojan","Movie"]},
{word:"Sultanate", taboo:["Delhi","Khalji","Lodhi","Tughlaq","India"]},
{word:"Khilafat", taboo:["Ottoman","Caliph","Gandhi","Congress","British"]},
{word:"Soldier", taboo:["Army","Military","Fighter","War","Officer"]},
{word:"Tactic", taboo:["Strategy","Method","Warfare","Military","Action"]},
{word:"Princess", taboo:["Prince","Queen","Daugther","Royal","Disney"]},
{word:"Uprising", taboo:["Revolt ","Rebellion","Attack","Insurrection","Mutiny"]},
{word:"Successor", taboo:["Next","Subsequent","Hereditary","Ruler","Follow"]},
{word:"Feast", taboo:["Banquet","Dinner","Celebration","Meal","Large"]},
{word:"Ceremony", taboo:["Function","Celebration","Occasion","Event","Act"]},
{word:"Illegitimate", taboo:["Unauthorised","Child","Wedlock","Married","Wrong"]},
{word:"Prisoner", taboo:["Jail","Captured","Punishment","Free","Inmate"]},
{word:"Conflict", taboo:["Fight","Issue","Disagreement","Argument","Clash"]},
{word:"Feudalism", taboo:["Class","Nobility","Land","System","Serfs"]},
{word:"Servant", taboo:["Worker","Lackey","Employed","Maid","Domestic"]},
{word:"Tower", taboo:["Lighthouse","Communication","Tall","Structure","Pillar"]},
{word:"Rank", taboo:["Position","Place","Order","Army","Military"]},
{word:"Tent", taboo:["Camp","Shelter","Pole","Rope","Erect"]},
{word:"Crown", taboo:["Symbol","Head","Ornament","King","Top"]},
{word:"Advisor", taboo:["Guidance","King","Plan","Recommendation","Person"]},
{word:"Archive", taboo:["Record","Store","Documents","Material","Papers"]},
{word:"Geneva", taboo:["Siwtizerland","Conference","Diplomacy ","Banking","City"]},
{word:"Artillery", taboo:["Infantry","Cavalry","Launch","Guns","Mortar"]},
{word:"Rights", taboo:["Fundamental","Declaration","Human","Principles","Rules"]},
{word:"Constitution", taboo:["Document","Laws","Articles","Aggregation","Compilation"]},
{word:"Ancestor", taboo:["Forefather","Descendant","Grandfather","Inherit","Genetic"]},
{word:"Capital ", taboo:["Delhi","City","Centre","Important","Major"]},
{word:"Cold War", taboo:["Us","Russia","America","Communism","Tension"]},
{word:"Churchill", taboo:["British","Pm","Politcian","Leader","World War"]},
{word:"Vietnam", taboo:["Us","War","Amercia","1960S","Asia"]},
{word:"Archaeology", taboo:["Study","Branch","Past","History","Time"]},
{word:"Nomads", taboo:["People","Community","Travel","Settle","Move"]},
{word:"Settlements", taboo:["Housing","Residence","Place","Colony","Community"]},
{word:"Modern", taboo:["Ancient","Progressive","Recent","Fresh","New"]},
{word:"Globalisation", taboo:["Process","Connected","Linked","Trade","Dependent"]},
{word:"Bronze", taboo:["Position","Third","Medal","Alloy","Copper"]},
{word:"Mahajanapadas", taboo:["Settlements","States","Kingdoms","Republics","Ancient"]},
{word:"Socrates", taboo:["Philosopher","Greek","Person","Thinker","Classical"]},
{word:"Peace", taboo:["War","Quiet","Silence","Harmony","Tranquility"]},
{word:"Dravidian", taboo:["Aryan","South","Indigenous","Original","Migrant"]},
{word:"Terracotta", taboo:["Clay","Ceramic","Baked","Burnt","Earthenware"]},
{word:"Classical", taboo:["Ancient","Dance","Music","Antique","Past"]},
{word:"Hindu Kush", taboo:["Mountain","India","Afghanistan","Passage","Invader"]},
{word:"Aztecs", taboo:["Community","Mexico","Spanish","Culture","Tribe"]},
{word:"Medieval", taboo:["Modern","Ancient","Outdated","Middle","Europe"]},
{word:"Barbarians", taboo:["Uncivilised","Invaders","Uneducated","Primitive","Humans"]},
{word:"Unification", taboo:["Partition","Germany","Berlin","Together","Whole"]},
{word:"Harshavardhana", taboo:["Emperor","King","Kannauj","Hieun-Tsang","Pulakeshin"]},
{word:"Constantinople", taboo:["Byzantine","Turkey","Roman","Capital","Istanbul"]},
{word:"Arabs", taboo:["Ethnic","Muslims","Saudi","Residents","Inhabitants"]},
{word:"Tughlaq", taboo:["Dynasty","Sultanate","Mohammed Bin","Delhi","Rulers"]},
{word:"Knight", taboo:["Soldier","Person","Nobility","Title","Fighter"]},
{word:"Humanism", taboo:["Philosophy","Belief","Man","Individual","System"]},
{word:"Century", taboo:["100","Years","Period","Time","Score"]},
{word:"Monotheism", taboo:["Single","Multiple","Religion","Worship","God"]},
{word:"Printing", taboo:["Press","Paper","Newspaper","Books","Physical"]},
{word:"Marco Polo", taboo:["Traveller","Explorer","Italian","Merchant","Europe"]},
{word:"Indigenous", taboo:["Native","Original","Inhabitant","Ehtnic","Natural"]},
{word:"Ibn Batuta", taboo:["Ishqiya","Travller","Morocco","Explorer","Medieval"]},
{word:"Metro", taboo:["Train","Delhi","Underground","Transport","Travel"]},
{word:"Sensor", taboo:["Device","Detect","Track","Sensitive","Senses"]},
{word:"Keyboard", taboo:["Typing","Alphabets","Peripheral","External","Computer"]},
{word:"Download", taboo:["Install","Computer","Desktop","Locally","Get"]},
{word:"Torrent", taboo:["Download","Illegal","Pirated","Pirate Bay","Website"]},
{word:"Spaceship", taboo:["Vehicle","Earth","Aliens","Travel","Machine"]},
{word:"Bug", taboo:["Error","Issue","Discrepancy","Function","System"]},
{word:"Fission", taboo:["Nuclear","Hydrogen","Energy","Generate","Huge"]},
{word:"Paytm", taboo:["Vijay Shekhar","Wallet","Payment","First","Demonetisation"]},
{word:"Toaster", taboo:["Bread","Electricity","Appliance","Breakfast","Thing"]},
{word:"Voice Assistant", taboo:["Alexa","Cortana","Talk","Speech","Understands"]},
{word:"Fan", taboo:["Ceiling","Table","Rotates","Air","Summers"]},
{word:"Hair Dryer", taboo:["Wet","Long","Bath ","Party","Pretty"]},
{word:"Speedgun", taboo:["Vehicle","Car","Speed","Fast","Device"]},
{word:"Podcast", taboo:["Listen","Audio","Streaming","Episodes","Service "]},
{word:"Helicopter", taboo:["Air","Military","Rotor","Fan","Sky"]},
{word:"Engagement", taboo:["Time","Addicted","Duration","App","Metric"]},
{word:"Geyser", taboo:["Warm","Water","Hot","Bath","Heat"]},
{word:"Tear-Gas", taboo:["Water","Police","Mob","Riot","Protest"]},
{word:"Dam", taboo:["Water","River","Hydorelectricity","Bhakra Nangal","Hirakud"]},
{word:"Welding", taboo:["Metal","Heat","Join","Materials","Energy"]},
{word:"Sundar Pichai", taboo:["Google","Ceo","Head","Company","Indian"]},
{word:"Projector", taboo:["Display","Screen","Show","Large","Different"]},
{word:"Acquisition", taboo:["Buy","Merge","Own","Purchase","Company"]},
{word:"Power Plant", taboo:["Nuclear","Thermal","Hydropower","Electricity","Facility"]},
{word:"Smartwatch", taboo:["Intelligent","Anrdoid","Wearable","Time","Tracking"]},
{word:"Iot", taboo:["Connected","Devices","Linked","System","Concept"]},
{word:"Digilocker", taboo:["Documents","Online ","Store ","Government","Service"]},
{word:"Bullet Train", taboo:["Modi","Bjp","Ahemadabad","Japan","Superfast"]},
{word:"Geek", taboo:["Nerd","Intelligent","Talented","Smart","Computers"]},
{word:"Engine", taboo:["Car","Railway","Every","Vehicle","Work"]},
{word:"Snooping", taboo:["Hack","Information","Monitor","Private","Data"]},
{word:"Fingerprint", taboo:["Crime","Authenticate","Identity","Crime","Ivestigation"]},
{word:"Rdx", taboo:["Explosive","Movie","Bomb","War","Military"]},
{word:"Space", taboo:["Sky","Up","Atmosphere","Over","Vast"]},
{word:"Evm", taboo:["Elections","Rigged","Machines","Voting","Blame"]},
{word:"Tesla", taboo:["Elon Musk","Electric ","Car","Automobile","Company"]},
{word:"Airpod", taboo:["Earphones","Wireless","Apple","Bluetooth","Music"]},
{word:"High-Definition", taboo:["Clear","Video","Image","Quality","Good"]},
{word:"Bulb", taboo:["Edison","Light","Yellow","Appliance","Device"]},
{word:"Walmart", taboo:["E-Commerce","Retail","Offline","Flipkart","Amazon"]},
{word:"Lightyear", taboo:["Time","Travel","Unit","Distance","Concept"]},
{word:"Printer", taboo:["Device","Page","E-Mail","Physical","Hard"]},
{word:"Artificial Intelligence", taboo:["Natural","Concept","Machines","Think","Human"]},
{word:"Rocket", taboo:["Space","Vehicle","Nasa","Isro","Launch"]},
{word:"Browser", taboo:["Chrome","Firefox","Safari","Opera","Internet"]},
{word:"Quora", taboo:["Website","Question","Answer","Platform","Knowledge"]},
{word:"Antenna", taboo:["Receive","Radio","Signal","Current","Dish"]},
{word:"Lg", taboo:["Company","Brand","Fridge","Appliances","Ac"]},
{word:"Tablet", taboo:["Computer","Small","Browsing","Videos","Ipad"]},
{word:"Einstein", taboo:["Relativity","Germany","Theory","Famous","Nobel"]},
{word:"Android", taboo:["Operating System","Google","Smartphone","Device","Product"]},
{word:"Offline", taboo:["Online","Physical","Retail","Turned-Off","Switch"]},
{word:"Facebook", taboo:["Social","Friends","Website","Company ","Family"]},
{word:"Dell", taboo:["Pc","Laptop","Computers","Inspiron","Devices"]},
{word:"Gps", taboo:["Location","Destination","Travel","System","Maps"]},
{word:"Softbank", taboo:["Venture Capital","Investment","Huge","Unicorn","Valuation"]},
{word:"Satellite", taboo:["Object","Orbit","Earth","Example","Space"]},
{word:"Synchronization", taboo:["Concurrent ","Same","Co-Ordinated","Together","Multiple"]},
{word:"Hacking", taboo:["Break Into","Breach","Exploit","Computer","System"]},
{word:"Java", taboo:["Language","Programming","Software","Computer","Object Oriented"]},
{word:"Self Driving Car", taboo:["Human","Driver","Vehicle","Manual","Person"]},
{word:"Cv Raman", taboo:["Scientist","Physics","Indian","Light","Nobel"]},
{word:"Open-Source", taboo:["Linux","Ubuntu","Contribute","Free","Code"]},
{word:"Whatsapp", taboo:["Chat","Message","Friends","Family","App"]},
{word:"Petrol", taboo:["Fuel","Car","Diesel","Vehicle","Crude"]},
{word:"Password", taboo:["Authentiate","Login","Open","Access","Forget"]},
{word:"Nasa", taboo:["Space","Organisation","Us","American","Research"]},
{word:"Premium", taboo:["Amount","Payment","Higher","More","Greater"]},
{word:"Spam", taboo:["Unwanted","Mail","Junk","Need","Unsolicited"]},
{word:"Radiation", taboo:["Mobile ","Telecom","Harmful","Invisible","Install"]},
{word:"Air Purifier", taboo:["Pollution","Filters","Cleans","Purifies","Surroundings"]},
{word:"Thermometer", taboo:["Temperature","Fever","Mercury","Device","Sick"]},
{word:"Code", taboo:["Programmer","Developer","Software","Create","Build"]},
{word:"Autonomous", taboo:["Manual","Intervention","Automatic","Robot","Car"]},
{word:"Wifi", taboo:["Internet","Office","Password","Home","Connect"]},
{word:"Magnet", taboo:["Attract","Repel","Polarity","Iron","Object"]},
{word:"Wireless", taboo:["Signals","Waves","Connected","Devices","Points"]},
{word:"Barcode", taboo:["Technology","Printed","Lines","Vertical","Data"]},
{word:"Microwave Oven", taboo:["Device","Food","Heating","Kitchen","Appliance"]},
{word:"Clone", taboo:["Similar","Genetic","Same","Identical","Exact"]},
{word:"Cockpit", taboo:["Aeroplane","Pilot","Sit","Area","Part"]},
{word:"Firefox", taboo:["Broswer","Chrome","Safari","Opera","Web"]},
{word:"Blogging", taboo:["Write","Online","Creative","Hobby","Wordpress"]},
{word:"Madam Curie", taboo:["Discover","Scientist","Female","Women","Research"]},
{word:"Missile", taboo:["Agni","Prithvi","Weapon","Technology","War"]},
{word:"Refresh", taboo:["Again","F5","Reload","Page","Change"]},
{word:"Climate Change", taboo:["Temperature","Rise","Increase","Ice-Caps","Earth"]},
{word:"Semiconductor", taboo:["Silicon","Device","Electricity","Material","Conduct"]},
{word:"Newton", taboo:["Gravity","Physics","Motion","Inertia","Scientist"]},
{word:"Bose", taboo:["Headphones","Earphones","Company","Best","Sound"]},
{word:"Generator", taboo:["Electricity","Motor","Diesel","Noise","Light"]},
{word:"Time Machine", taboo:["Travel","Fiction","Future","Past","Device"]},
{word:"Nanotechnology", taboo:["Industry","Small","Micro","Sector","Size"]},
{word:"Stove", taboo:["Kitchen","Appliance","Cook","Heat","Warm"]},
{word:"Computer", taboo:["Laptop","Home","Electronic","Windows","Desktop"]},
{word:"Hardware", taboo:["Software","Physical","Tangible","Real","Component"]},
{word:"Cd", taboo:["Compact Disc","Movies","Games","Childhood","Kids"]},
{word:"Unzip", taboo:["Large","Compress","Single","Reduce","Size"]},
{word:"Stephen Hawking", taboo:["Scientist","Physics","Time","Famous","Nobel"]},
{word:"Steam Press", taboo:["Method","Iron","Clothes","Electric ","Way"]},
{word:"App", taboo:["Mobile","Example","Types","Smartphone","Android"]},
{word:"Techcrunch", taboo:["Website","Technology","Online","Company","Industry"]},
{word:"Tower", taboo:["Mobile","Telecom","Radiation","Eiffel","Leaning"]},
{word:"Format", taboo:["Type","Support","File","Differentiate","Play"]},
{word:"Earphone", taboo:["Device","Music","Plug","Jbl","Senheiser"]},
{word:"Prosthetic", taboo:["Artificial","Limb","Body-Part","Leg","Arm"]},
{word:"Motion", taboo:["Travel","Movement","Direction","Newton","Change"]},
{word:"Anaesthesia", taboo:["Operation","Numb","Unconscious","Pain","Chloroform"]},
{word:"Cloud Computing ", taboo:["Aws","Azure","Server","Physical","Online"]},
{word:"Air Conditioner (Ac)", taboo:["Temperature","Houses","Cooling","Machine","Device"]},
{word:"Chandrayaan", taboo:["Isro","Moon","Vikram","Crash","Mission"]},
{word:"Machine Gun", taboo:["Automatic","Kill","Bullets","Fire","Ak-47"]},
{word:"Fintech", taboo:["Sector","Digital","Banks","Payment","Wallet"]},
{word:"Thermos", taboo:["Flask","Temperature","Hot","Maintain","Vaccum"]},
{word:"Mastercard", taboo:["Debit Card","Credit Card","Payments","Company","Visa"]},
{word:"Walkman", taboo:["Sony","Music","Device","Portable","Famous"]},
{word:"Servicing", taboo:["Repair","Maintainence","Centre","Car","Vehicle"]},
{word:"Laboratory", taboo:["Experiment","Research","Scientist","Innovation","Test Tube"]},
{word:"Upi", taboo:["Payment","Bhim","Google Pay","Smartphone","Transaction"]},
{word:"Cybercrime", taboo:["Hack","Fraud","Category","Password","Phishing"]},
{word:"Cooker", taboo:["Dal","Rice","Pressure","Hawkins","Appliance"]},
{word:"Transplant", taboo:["Liver","Heart","Kideney","Extract","Cut"]},
{word:"Steve Jobs", taboo:["Apple","Iphone","Ipad","Ipod","Mac"]},
{word:"Marissa Mayer", taboo:["Google","Yahoo","Technology","Women","Leader"]},
{word:"Broadband", taboo:["Internet","Home","Modem","Term","Wifi"]},
{word:"Install", taboo:["Download",".Exe","Application","Run","Use"]},
{word:"Patent", taboo:["Innovation","Discovery","Royalty","Money","Create"]},
{word:"Bulldozer", taboo:["Destruction","Demolition","Machine","Vehicle","Crane"]},
{word:"Email", taboo:["Gmail","Outlook","Communication","Office","Digital"]},
{word:"Chromecast", taboo:["Stream","Smart ","Google ","Digital","Device"]},
{word:"Lift", taboo:["Elevator","Stairs","Building","Complex","Floor"]},
{word:"Spotify", taboo:["Music","Streaming","App","Listen","Popular"]},
{word:"Submarine", taboo:["Underwater","Machine","Vehicle","Subsurface","Innovation"]},
{word:"Yahoo", taboo:["Email","Search","Google","Msn","Messenger"]},
{word:"Bill Gates", taboo:["Microsoft","Richest","Ceo","Windows","Founder"]},
{word:"Gravity", taboo:["Space","Earth","Apple","Newton","Phenomenon"]},
{word:"Chatbot", taboo:["Customer Service","Technology","Software","Conversation","Artificial Intelligence"]},
{word:"Invisible", taboo:["Vision","Seep","Eyes","Hidden","Inaccessible"]},
{word:"Current", taboo:["Wires","Metal","Appliance","Shock","Electricity"]},
{word:"Netflix", taboo:["Video Steaming","Similar","Famous","Popular","Service"]},
{word:"Robot", taboo:["Automation","Japan","Small Wonder","Asimov","Machine"]},
{word:"Edtech", taboo:["Field","Sector","Domain","Technology","Companies"]},
{word:"Micromax", taboo:["Low-Cost","Mobile","Smartphones","Intex","Karbonn"]},
{word:"Jack Ma", taboo:["Alibaba","Entrepreneur","Paytm","Chinese","E-Commerce"]},
{word:"Xiaomi", taboo:["Company","Smartphone","Brand","Chinese","Indian"]},
{word:"Swiss Knife", taboo:["Multi-Purpose","Different","Special","Unique","Use"]},
{word:"Uber", taboo:["Taxi","Pool","Moto","Cab","Ride"]},
{word:"Breath Analyzer", taboo:["Alcohol","Police","Driving","Car","Device"]},
{word:"Server", taboo:["Storage","Online","Website","Host","Machine"]},
{word:"Alloy", taboo:["Mix","Metal","Brass","Bronze","Nickel"]},
{word:"Gorilla Glass", taboo:["Unbreakable","Screen","Smartphone","Strengthened","Resistant"]},
{word:"Jacuzzi", taboo:["Bathtub","Water","Bathroom","Company","Shower"]},
{word:"Tractor", taboo:["Farmers","Farms","Open","Crops","Agriculture"]},
{word:"Bulletproof", taboo:["Movies","Die","Kill","Protect","Save"]},
{word:"Personalisation", taboo:["Targetted","Specific","Websites","Experience","Behaviour"]},
{word:"Biometric", taboo:["Authentication","Aadhaar","Fingerprint","Eye","Scan"]},
{word:"Biogas", taboo:["Gobargas","Cowdung","Fuel","Organic","Decomposition"]},
{word:"Data", taboo:["Mobile","Internet","Plan","Information","Big"]},
{word:"Raspberry Pi", taboo:["Computer","Small","Hands","Chip","Machine"]},
{word:"Telescope", taboo:["Device","Astronomy","Space","Stars","Observe"]},
{word:"Virus", taboo:["Computer","Malware","Spyware","Disease","Microbe"]},
{word:"Batmobile", taboo:["Joker","Chiristopher Nolan","Car","Vehicle","Device"]},
{word:"Detector", taboo:["Device","Instrument","Identifies","Discovers","Presence"]},
{word:"Awareness", taboo:["Know","Information","Idea","Conscious","Happening"]},
{word:"Waterproof", taboo:["Resistant","Seep","Leak","Impervious","Prevent"]},
{word:"Qr Code", taboo:["Matrix","Rectangle","App","Install","Dots"]},
{word:"Virtual Reality", taboo:["Technology","Person","Real","Device","Simulate"]},
{word:"Invent", taboo:["Find","Make","Build","Produce","Create"]},
{word:"Mining", taboo:["Metal","Extraction","Earth","Surface","Underground"]},
{word:"Lenovo", taboo:["Battery","Laptop","Computers","Thinkpad","Devices"]},
{word:"Touchscreen", taboo:["Feature","Smartphones","Computers","Hand","Fingers"]},
{word:"Airbnb", taboo:["Company","Start-Up","Homestays","Lodging","Marketplace"]},
{word:"Payment", taboo:["Online","E-Wallet","Digital","Purchase","Shop"]},
{word:"X-Ray", taboo:["Fracture","Technology","Scan","Bones","Inside"]},
{word:"Tap", taboo:["Water","Bathroom","Kitchen","Toilet","Use"]},
{word:"Secure", taboo:["Safe","Protected","Password","Hack","Firm"]},
{word:"Dynamic Pricing", taboo:["Demand","Surge","Technique","Fare","Higher"]},
{word:"Headphones", taboo:["Listen","Music","Ear","Plug","Device"]},
{word:"Kindle", taboo:["Reading","Book","Device","Amazon"," Tablet"]},
{word:"Captcha", taboo:["Login","Password","Authenticate","Technique","System"]},
{word:"Drone", taboo:["Device","Air","Ground","Camera","Video"]},
{word:"Camera", taboo:["Photo","Picture","Click","Selfie","Phone"]},
{word:"Aws (Amazon Web Services)", taboo:["Cloud","Server","Amazon","Storage","Services"]},
{word:"Pen Drive", taboo:["Storage","Additional","1Gb/2Gb/4Gb/8Gb","Sandisk","Capacity"]},
{word:"Flush", taboo:["Toilet","Morning","Dump","Eat","Water"]},
{word:"Charger", taboo:["Device","Mobile","Smartphone","Laptop","Energy"]},
{word:"Scan", taboo:["Device","Convert","Image","Reads","Document"]},
{word:"Cisco", taboo:["Company","Networks","Routers","Software","Organisation"]},
{word:"Vaccine", taboo:["Disease","Germs","Children","Microbes","Polio"]},
{word:"Fake-News", taboo:["Cambridge Analytica","Facebook","Social Media","Rumour","Incorrect"]},
{word:"Bitcoin", taboo:["Cryptocurrency","Blockchain","Money","Finance","Digital"]},
{word:"Elon Musk", taboo:["Tesla","Ironman","Electric","Hyperloop","Paypal"]},
{word:"Encryption", taboo:["Password","Data","Whatsapp","Technology","Protect"]},
{word:"Intel", taboo:["Company","Chips","Computer","Microprocessor","Mnc"]},
{word:"Aeroplane", taboo:["Flight","Sky","Pilot","Air-Hostess","Airport"]},
{word:"Broadcast", taboo:["Announce","Message","Inform","Eveyone","Send"]},
{word:"Fastag", taboo:["Toll","Rfid","Device","Payment","Technology"]},
{word:"Nokia", taboo:["Company","Phone","Finland","Mobile","1100"]},
{word:"Electrolysis", taboo:["Electricity","Breakdown","Transform","Convert","Current"]},
{word:"Website", taboo:["Browser","Facebook","Google","Type","Category"]},
{word:"Fitbit", taboo:["Health","Running","Device","Wearable","Company"]},
{word:"Jio", taboo:["Reliance","Telecom","Network","Dataplan","Free"]},
{word:"4G", taboo:["Jio","Spectrum","1G/2G/3G","Communication","Phone"]},
{word:"Refrigrator", taboo:["Appliance","Cold","Ice","Home","House"]},
{word:"Satya Nadella", taboo:["Microsoft","Ceo","Windows","Company","Organisation"]},
{word:"Contact Lens", taboo:["Eyes","Spectacles","Vision","See","Glasses"]},
{word:"Cache", taboo:["Store","Quick","Fast","Efficient","Future"]},
{word:"Privacy        (Data Privacy)", taboo:["Security","Consent","Information","Share","Own"]},
{word:"Communication", taboo:["Talk","Telecom","Electronics","Speak","Signal"]},
{word:"Automation", taboo:["Manual","Mechanisation","Replace","Humans","Control"]},
{word:"Philips", taboo:["Tubelight","Electronics","Bulb","Trimmer","Appliance"]},
{word:"Catalyst", taboo:["Reaction","Enzyme","Fast","Speedens","Hastens"]},
{word:"Usb", taboo:["Standard","Interface","Connecting","Peripheral","Computer"]},
{word:"Heater", taboo:["Temperature","Winters","Warm","Hot","Room"]},
{word:"Ultrasound", taboo:["Birth","Gender","Technique","Imaging","Diagnostic"]},
{word:"Galvanization", taboo:["Zinc","Rust","Iron","Coating","Process"]},
{word:"Tubelight", taboo:["Home","Electricity","Bulb","House","Device"]},
{word:"Sim Card", taboo:["Mobile ","Smartphone","Thing","Dual","Insert"]},
{word:"Drilling", taboo:["Screw","Hole","Machine","House","Hang"]},
{word:"Start-Up", taboo:["Small","New","Entrepreneur","Many","Few"]},
{word:"Loudspeaker", taboo:["Airport","Religious","Sound","Function","Marriage"]},
{word:"Autopilot", taboo:["Manual","Hands-Off","Machine","Intervention","Aeroplane"]},
{word:"Pacemaker", taboo:["Heart","Device ","Slow","Irregular","Heartbeat"]},
{word:"Bluetooth", taboo:["Standard","Transfer","Send","Wireless","Connect"]},
{word:"Laser", taboo:["Technology","Pinpoint","Exact","Device","Light"]},
{word:"Youtube", taboo:["App","Music","Google","Videos","Watch"]},
{word:"Supercomputer", taboo:["Capability","Extraordinary","Performance","Fast","Speed"]},
{word:"Boomerang", taboo:["Instagram","Photo","Back","Mini-Videos","Loop"]},
{word:"Oracle", taboo:["Database","Server","Larry Ellison","Backend","Technology"]},
{word:"Programmer", taboo:["Code","Computer","Person","Software","Creates"]},
{word:"Motorcycle", taboo:["Types","Brands","Two-Wheeler","Bike","Vehicle"]},
{word:"Bomb", taboo:["Explosive","War","Destruction","Battlefield","Terrorists"]},
{word:"Radio", taboo:["Fm","Rj","Car","Hear","Listen"]},
{word:"Rotate", taboo:["Move","Circular","Round","Motion","Wheel"]},
{word:"Speaker", taboo:["Music","Audio","Apmplify","Loud","Listen"]},
{word:"Anonymous", taboo:["Unknown","Reveal","Login","Name","Identity"]},
{word:"Iphone", taboo:["Steve Jobs","Apple","Expensive","Smartphone","Android"]},
{word:"Battery", taboo:["Mobile","Smartphone","Charge","Devices","Power"]},
{word:"Speedometer", taboo:["Car","Vehicle","Fast","Slow","Device"]},
{word:"Tiktok", taboo:["Videos","Bytedance","Millenials","App","Short"]},
{word:"Launch", taboo:["Release","Start","Open","Application","Platform"]},
{word:"Steel", taboo:["Stainless","Utensils","Iron","Construction","Strength"]},
{word:"Experiment", taboo:["Trial","Pilot","Test","Demonstrate","Laboratory"]},
{word:"Signal", taboo:["Mobile","Connectivity","Reception","Receive","Network"]},
{word:"Snapdragon", taboo:["Processor","Qualcom","Smartphones","Technology","Mobile"]},
{word:"Unicorn", taboo:["Start-Up","Billion","Valuation","Uber","Creature"]},
{word:"Cookie", taboo:["Biscuit","Website","Internet","Information","Save"]},
{word:"Silicon Valley", taboo:["Innovation","Companies","Us","Technology","Place"]},
{word:"Storage", taboo:["Space","Hard Disk","Capacity","Safe","Capture"]},
{word:"3D Glass", taboo:["Movies","Theatre","Illusion","Technology","Device"]},
{word:"Talisman", taboo:["Lucky","Charm","Astrologet","Stone","Luck"]},
{word:"Paris", taboo:["Fashion","Week","City","France","Eiffel"]},
{word:"Boots", taboo:["Military","Shoe","Ankle","Black","Army"]},
{word:"Fusion", taboo:["Mixture","Combination","Western","Nuclear","Indo"]},
{word:"Lungi", taboo:["Sarong","Skirt","Dhoti","Garment","Body"]},
{word:"Wraparound", taboo:["Fold","Closed","Wrapping","Side","Across"]},
{word:"Dupatta", taboo:["Scarf","Chudidar","Chunri/Odhni","Salwar","Cover"]},
{word:"Jhola", taboo:["Bag","Cloth","Journalist","Women","Shoulder"]},
{word:"Locket", taboo:["Pendant","Necklace","Chain","Love","Gold"]},
{word:"Lip Gloss", taboo:["Shine","Lustre","Glittery","Face","Product"]},
{word:"Wallet", taboo:["Purse","Money","Id Card","Leather","Black"]},
{word:"Photoshot", taboo:["Model","Camera","Pose","Photographer","Pictures"]},
{word:"Sneakers", taboo:["Shoes","Sports","Casual","Running","Rubber"]},
{word:"Bindi", taboo:["Forehead","Dot","Married","Red","Face"]},
{word:"Tailor", taboo:["Stitch","Master Ji","Clothes","Person","Professional"]},
{word:"Brooch", taboo:["Pin ","Jewellery","Decorative","Attached","Fabric"]},
{word:"Cosmetics", taboo:["Artificial","Substances","Products","Appearance","Texture"]},
{word:"Capris", taboo:["Knees","Shorts","Pants","Trousers","Ankles"]},
{word:"Symmetry", taboo:["Identical","Mirror","Same","Balanced","Shapes"]},
{word:"Bell-Bottom", taboo:["Trousers","Retro","Wider","Style","Older"]},
{word:"Influencer", taboo:["Social","Following","Fans","Popular","Famous"]},
{word:"Motif", taboo:["Decoration","Design","Recurring","Repeating","Image"]},
{word:"Mannequin", taboo:["Clothes","Hanging","Shops","Model","Doll"]},
{word:"Handmade", taboo:["Stitched","Manual","Created","Machine","Automatic"]},
{word:"Retail", taboo:["Shop","Purchase","Store","Sell","Buy "]},
{word:"Salwar", taboo:["Kameez","Suit","Traditional","Indian","Clothing"]},
{word:"Belt", taboo:["Leather","Tied","Waist","Jeans","Pants"]},
{word:"Benarasi", taboo:["Saree","Holy","Varanasi","City","Silk"]},
{word:"Ethnic", taboo:["Traditional","Clothes","Dresses","Culture","Category"]},
{word:"Cosplay", taboo:["Dress","Comicon","Character","Wear","Costumes"]},
{word:"Ensemble", taboo:["Group","Together","Performance","Cast","Equal"]},
{word:"Display", taboo:["Show","Demonstrate","See","Visible","Public"]},
{word:"Scarf", taboo:["Cover","Cloth","Neck ","Warmth","Fabric"]},
{word:"Watch", taboo:["Time","Wear","Hand","Accessory","Wrist"]},
{word:"Victoria'S", taboo:["Secret","Lingerie","Underwear","Innerwear","Supermodel"]},
{word:"Budget", taboo:["Money","Limit","Plan","Amount","Fixed"]},
{word:"Wardrobe", taboo:["Closet ","Storage","Clothes","Almirah","Cupboard"]},
{word:"Masculine", taboo:["Male","Strong","Heavy","Feminine","Tough"]},
{word:"Sunglasses", taboo:["Goggles","Shades","Glares","Eyes","Black"]},
{word:"Maang Tikka", taboo:["Jewelry","Forehead","Hair","Accessory","Middle"]},
{word:"Barrette", taboo:["Hair ","Ornament","Clip ","Clasp","Head"]},
{word:"Bracelet", taboo:["Wrist","Arm","Jewellery","Ornament","Gift"]},
{word:"Milan", taboo:["Fashion","Capital","Quality","Destination","Textiles"]},
{word:"Veil", taboo:["Burqa","Black","Cover","Face","Head"]},
{word:"Sketch", taboo:["Paint","Sample","Look","Design","Drawing"]},
{word:"Unisex", taboo:["Both","Wear","Female","Male","Gender"]},
{word:"Grooming", taboo:["Cleaning","Shaving","Brushing","Maintaining","Hygiene"]},
{word:"Thong", taboo:["G-String","Underwear","Panty","Small","Garment"]},
{word:"Off-Shoulder", taboo:["Blouse","Top","Clothing","Cover","Visible"]},
{word:"Watch", taboo:["Time","Wrist","Clock","Apple ","Smart"]},
{word:"Minimalism", taboo:["Simple","Less","Modest","Declutter","Few"]},
{word:"Agent", taboo:["Individual","Manager","Person","Work","Affairs"]},
{word:"Sparkling", taboo:["Shining","Glittering","Diamond","Pearl","Gold"]},
{word:"Jersey", taboo:["Cricket","Sports","Football","Shirt","Atheletes"]},
{word:"Antique", taboo:["Past","Old","Vintage","Historical","Dated"]},
{word:"Distinct", taboo:["Different","Unique","Special","Same","Similar"]},
{word:"Trial Room", taboo:["Purchase","Shop","Clothes","Before","Buying"]},
{word:"Camisole", taboo:["Loose","Sleeveless","Undergarment","Women","Ladies"]},
{word:"Casual", taboo:["Relaxed","Informal","Everyday","Daily","Ordinary"]},
{word:"Maxi", taboo:["Loose","Full-Length","Women","Ladies","Dress"]},
{word:"Abstract", taboo:["Tangible","Concrete","Real","Summary","Symbol"]},
{word:"Makeover", taboo:["Transformation","Change","Appearance","Looks","Alter"]},
{word:"Drape", taboo:["Cover","Saree","Arrange ","Around","Casual"]},
{word:"L'Oreal", taboo:["French","Beauty","Care","Cosmetics","Skin"]},
{word:"Exchange", taboo:["Retun","Different","Currency","Shop","Back"]},
{word:"Bikini", taboo:["Beach","Swimwear","Two-Piece","Holiday","Women"]},
{word:"Moustache", taboo:["Nose","Face","Beard","Hair","Lips"]},
{word:"Choli", taboo:["Lehenga","Blouse","Skirt","Traditional","Marriage"]},
{word:"Jacket", taboo:["Garment","Warm","Hood","Leather","Winter"]},
{word:"Garland", taboo:["Flowers","String","Arrangement","Decorative","Leaves"]},
{word:"Market", taboo:["Place","Buy","Purchase","Stuff","Dresses"]},
{word:"Chapstick", taboo:["Lip","Dry","Cosmetic","Balm","Brand"]},
{word:"Street", taboo:["Road","Fashion","Thoroughfare","Colaba","Clothes"]},
{word:"Shades", taboo:["Colours","Sunglasses","Goggles","Aviators","Grey"]},
{word:"Robe", taboo:["Bathing","Gown","Garment","Housecoat","Home"]},
{word:"Feminine", taboo:["Ladylike","Curvy","Delicate","Women","Qualities"]},
{word:"Lbd", taboo:["Little","Black ","Dress","Party","Cocktail"]},
{word:"Bracelet", taboo:["Wrist","Jewelry","Band","Thoran","Friends"]},
{word:"Tuxedo", taboo:["Suit","Two-Piece","Coat","Jacket","Men"]},
{word:"Aesthetics", taboo:["Nature","Nice","Sense","Beauty","Taste"]},
{word:"Gift", taboo:["Special","Free","Anniversary","Present","Birthday"]},
{word:"Shawl", taboo:["Loose","Winters","Body","Cover","Women"]},
{word:"Diamond", taboo:["Jewellery","Sparkling","Women","Expensive","Carbon"]},
{word:"Sabyasachi", taboo:["Designer","Weddings","Dresses","Nift","Famous"]},
{word:"Wig", taboo:["Artificial","Hair","Bald","Cover","Head"]},
{word:"Fancy", taboo:["Special","Unique","Amazing","Decorated","Different"]},
{word:"Heels", taboo:["Stilletos","High","Pencil","Shoes","Tall"]},
{word:"Sweater", taboo:["Wool","Winter","Warm","Wear","Garment"]},
{word:"Pedicure", taboo:["Treatment","Cosmetic","Feet","Toenails","Manicure"]},
{word:"Hairband", taboo:["Hair","Accessory","Curve","School","Headband"]},
{word:"Supermodel", taboo:["Fashion","Rampwalk","Brands","Term","Rich"]},
{word:"Extensions", taboo:["Length","Colour","Hair","Nails","Long"]},
{word:"Burqa", taboo:["Muslim","Women","Black","Cover","Abaya"]},
{word:"Ombre", taboo:["Shaded","Colour","Hair","Blend","Gradient"]},
{word:"Halter Top", taboo:["Dress","Tied","Sleveless","Neck","Straps"]},
{word:"Collection", taboo:["Clothes","Fashion","Set ","Group","Similar"]},
{word:"Glamorous", taboo:["Fashionable","Modern","Beauty","Attractive","Appealing"]},
{word:"Vintage", taboo:["Retro","Olden","Past","Quality","Wine"]},
{word:"Jhumka", taboo:["Ears","Bareily","Jewelry","Bride","Pendant"]},
{word:"Apron ", taboo:["Cooking","Cloth","Kitchen","Front","Body"]},
{word:"Tunic", taboo:["Shirt","Sweater","Garment","Upper","Body"]},
{word:"Camera", taboo:["Lens","Image","Click","Smartphone","Selfie"]},
{word:"Corduroy", taboo:["Textile","Durable","Colour","Cord","Fabric"]},
{word:"Myntra", taboo:["E-Commerce","Website","Online","Shopping","Website"]},
{word:"Versace", taboo:["Italian","Luxury","Fashion","Clothing","Brand"]},
{word:"Juthi", taboo:["Shoes","Indian","Wedding","Groom","Traditional"]},
{word:"Fad", taboo:["Trend","Temporary","Craze","Permanent","Short-Lived"]},
{word:"Contour", taboo:["Makeup","Brush","Cheeks","Highlight","Outline"]},
{word:"Celebrity", taboo:["Popular","Famous","Actor","Actress","Star"]},
{word:"Stylist", taboo:["Celebrities","Fashion","Wear","Dresses","Person"]},
{word:"Dressmaker", taboo:["Tailor","Designer","Custom","Clothing","Profession "]},
{word:"Statement", taboo:["Expression","Style","Symbolise","Clear","Authentic"]},
{word:"Classic", taboo:["Quality","Masterpiece","Timeless","Outstanding","Unmatched"]},
{word:"Nail Polish", taboo:["Nail","Colour","Enamel","Finger","Nykaa"]},
{word:"Khaki", taboo:["Brown","Military","Police","Colour","Uniform"]},
{word:"Cosmopolitan", taboo:["Cultures","Diverse","Cities","Traveller","Variety"]},
{word:"Bandana", taboo:["Headband","Kerchief","Sweatband","Neck","Cool"]},
{word:"Bun", taboo:["Hairstyle","Circular","Round","Head","Back"]},
{word:"Functional", taboo:["Useful","Purpose","Role","Practical","Specifically"]},
{word:"Look", taboo:["See","Watch","Fashion","Style","View"]},
{word:"Manufacture", taboo:["Create ","Build","Produce","Factory","Industry"]},
{word:"Boutique", taboo:["Shop","Store","Jewellery","Clothes","Accessories"]},
{word:"Nightie", taboo:["Nightwear","Loose","Sleeping","Women","Bed"]},
{word:"Customer", taboo:["Shop","Business","Buy","Store","Person"]},
{word:"Neckline", taboo:["Cut","Top","Edge","Garment","Front"]},
{word:"Bindi", taboo:["Forehead","Women","Dot","Kumkum","Eyes"]},
{word:"Chiffon", taboo:["Fabric","Cloth","Gowns","Woven","Decorative"]},
{word:"Chic", taboo:["Stylish","Cool","Elegant","Smart","Fashion"]},
{word:"Formal", taboo:["Serious","Official","Proper","Wear","Tie"]},
{word:"Shopping", taboo:["Buying","Purchasing","Clothes","Online","E-Commerce"]},
{word:"Wreath", taboo:["Flowers","Ring","Ornament","Circular","Decoration"]},
{word:"Size", taboo:["Xs;S;M…","32;34;36…","Measurements","Changing Room","Fitting"]},
{word:"Ponytail", taboo:["Hairstyle","Secured","Back","Head","Long"]},
{word:"Season", taboo:["Summer","Winters","Autumn","Spring","Months"]},
{word:"Calvin Klein", taboo:["Luxury","Fashion","Underwear","Jeans","Apparels"]},
{word:"Sindoor", taboo:["Women","Married","Hair","Forehead","Partition"]},
{word:"Clovia", taboo:["Brand","Lingerie","Nightwear","Women","Ladies"]},
{word:"Style", taboo:["Trend","Fashion","Sense","Clothes","Cool"]},
{word:"Brace", taboo:["Support","Steady","Straps","Ready","Device"]},
{word:"Fabric", taboo:["Cloth","Material","Texture","Colour","Stuff"]},
{word:"Sexy", taboo:["Beautiful","Hot","Stimulating","Erotic","Attractive"]},
{word:"Bangles", taboo:["Married","Bracelet","Women","Hands","Arms"]},
{word:"Creation", taboo:["Make","Build","Existence","Manufacture","Engender"]},
{word:"Reversible", taboo:["Both","Sides","Either","Right","Around"]},
{word:"Embroidery", taboo:["Design","Pattern","Decoration","Stitching","Thread"]},
{word:"Gel", taboo:["Hair","Spikes","Rigid","Stand","Apply"]},
{word:"Symbol", taboo:["Sign","Icon","Mark","Indicator","Visual"]},
{word:"Bata", taboo:["Shoes","Footwear","School","Leather","Slippers"]},
{word:"Elegant", taboo:["Graceful","Dignified","Beautiful","Classy","Stylish"]},
{word:"Flip-Flop", taboo:["Slippers","Sandals","Casual","Flat ","Footwear"]},
{word:"Purse", taboo:["Money","Wallet","Cards","Leather","Clutch"]},
{word:"Umbrella", taboo:["Rain","Rihanna","Downpour","Weather","Protect"]},
{word:"Material", taboo:["Fabric","Base","Raw","Substance","Makes"]},
{word:"Makeup", taboo:["Cosmetic","Facial","Foundation","Moisturize","Look"]},
{word:"Perfume", taboo:["Deodrant","Spray","Fragrance","Aroma","Scent"]},
{word:"Pyjamas", taboo:["Nightsuit","Sleep","Clothes","Nightwear","Clothing"]},
{word:"Mangalsutra", taboo:["Marriage","Wedding","Necklace","Bride","Women"]},
{word:"Camouflage", taboo:["Military","Hidden","Blend","Disguise","Dye"]},
{word:"Skirt", taboo:["Waist","Legs","Lehenga","Avoid","Women"]},
{word:"Socialite", taboo:["Hilton","Person","Society","Gatherings","Events"]},
{word:"Kanjeevaram", taboo:["Kanchipuram","Tamil Nadu","Saree","Silk","Bridals"]},
{word:"Ootd", taboo:["Outfit","Acronym","Dress","Clothing","Day"]},
{word:"Discount", taboo:["Reduce","Decrease","Less","Price","Money"]},
{word:"Trimming", taboo:["Shorten","Cutting","Machine","Haircut","Length"]},
{word:"Collar", taboo:["Tie","Shirt","Coat","Neck","Dress"]},
{word:"Cufflinks", taboo:["Hold","Join","Shirt","Buttons","Tools"]},
{word:"Kaftan", taboo:["Robe ","Tunic","Loose","Sleeves","Royalty"]},
{word:"Designer", taboo:["Fashion","Clothes","Tailor","Interior","Person"]},
{word:"Dungaree", taboo:["Jeans","Overalls","Straps","Denim","Cloth"]},
{word:"Lifestyle", taboo:["Way","Activities","Interests","Dressing","Choices"]},
{word:"Ramp Walk", taboo:["Model","Runway","Show","Designer","Fashion"]},
{word:"Figure", taboo:["Shape","Size","Model","Weight","Looks"]},
{word:"Sequin", taboo:["Stars","Glitters","Dress","Shining","Decoration"]},
{word:"Fashionista", taboo:["Current","Style","Person","Follower","Devoted"]},
{word:"Jumpsuit", taboo:["One-Piece","Prachuters","Sky-Divers","Garment","Women"]},
{word:"Madame", taboo:["Brand","Ludhiana","Women","Girls","Clothing"]},
{word:"Cocktail", taboo:["Wine","Party","Dress","Alcohol","Mocktail"]},
{word:"Texture", taboo:["Quality","Surface","Look","Art","Colour"]},
{word:"Slim-Fit", taboo:["Skinny","Size","Tight","Legs","Exact"]},
{word:"Package", taboo:["Box","Delivery","Gift","Parcel","Wrapped"]},
{word:"Mehendi", taboo:["Hand","Henna","Design ","Art","Bride"]},
{word:"Swag", taboo:["Cool","Stylish","Classy","Elegant","Attitude"]},
{word:"Accessories", taboo:["Jewelry","Clothes","Look","Bag","Item"]},
{word:"Shampoo", taboo:["Hair","Liquid","Conditioner","Product","Dandruff"]},
{word:"Luxury", taboo:["Expensive","Pricey","Money","Sophisticated","Classy"]},
{word:"Choker", taboo:["Necklace","Women","Ladies","Fitting","Jewellery"]},
{word:"Fabulous", taboo:["Great","Amazing","Extraordinary","Fantastic","Gorgeous"]},
{word:"Sarees", taboo:["Indian","Traditional","Marriage","Bride","Wrapped"]},
{word:"Turtleneck", taboo:["Pullover","Polo Neck","Sweater","Black","Round"]},
{word:"Hat", taboo:["Cowboy","Cap ","Head","Cover","Top"]},
{word:"Brand", taboo:["Label","Types","Examples","Name","Term"]},
{word:"Costume", taboo:["Dress","Style","Clothing","Type","Wear"]},
{word:"Bandhini", taboo:["Textile ","Fabric","Bindings","Handwoven","Design"]},
{word:"Mufflers", taboo:["Winters","Neck ","Warm","Accessory","Around"]},
{word:"Lakme", taboo:["Face","Fashion","Cosmetics","Hul","Cream"]},
{word:"Keychain", taboo:["Keys","Lock","Ring","Accessory","Object"]},
{word:"Trouser", taboo:["Pant","Shirt","Jeans","Dress","Body"]},
{word:"Sweatshop", taboo:["Factory","Wages","Cloth","Manufacture","Low"]},
{word:"Pencil Skirt", taboo:["Corporate","Slim","Fitting","Narrow","Straight"]},
{word:"Sportswear", taboo:["Exercise","Sports","Physical","Fitness","Clothes"]},
{word:"Stitching", taboo:["Sewing","Clothes","Fitting","Knitting","Embriodery"]},
{word:"Sandals", taboo:["Shoes","Open","Strap","Flats","Footwear"]},
{word:"Stockings", taboo:["Leggings","Fitting","Garments","Legs","Length"]},
{word:"Kurti", taboo:["Women","Pajama","Indian","Jeans","Short"]},
{word:"Appearance", taboo:["Looks","See","Impresssion","Outward","External"]},
{word:"Singlet", taboo:["Undershirt","Undergarment","Sleveless","Athletes","Banyan"]},
{word:"Blouse", taboo:["Saree","Garment","Petticoat","Women","Shirt"]},
{word:"Mule", taboo:["Shoe","Back","Style","Horse","Donkey"]},
{word:"Comb", taboo:["Hair","Brush","Tooth","Bristles","Style"]},
{word:"Goatee", taboo:["Face","Hair","Moustache","Beard","Chin"]},
{word:"Tanishq", taboo:["Tata","Jewellery","Brand ","Gold","Diamond"]},
{word:"Thermal", taboo:["Winters","Warmer","Sweater","Innerwear","Cold"]},
{word:"Hemline", taboo:["Edge","Lower","End","Line","Skirt"]},
{word:"Pashmina", taboo:["Kashmir","Wool","Fine","Shawl","Textiles"]},
{word:"Stripe", taboo:["Lines","Pattern","Shirt","Band","Design"]},
{word:"Nift", taboo:["Institute","Fashion","Place","Study","Students"]},
{word:"Outfit", taboo:["Dress","Clothes","Party","Garments","Particular"]},
{word:"Cotton", taboo:["White","Fluffy","Light","Soft","Wipe"]},
{word:"Backpack", taboo:["Bag","Travel","Trekking","Hiking","Rucksack"]},
{word:"Turban", taboo:["Head","Cloth","Wrap","Sikh","Wound"]},
{word:"Earrings", taboo:["Accessories","Face","Jewellery","Pierce","Gold"]},
{word:"Floral", taboo:["Flowers","Patterns","Print","Feminine","Summers"]},
{word:"Gajra", taboo:["Hair","Flowers","Love","Head","Round"]},
{word:"Zara", taboo:["Women","Apparel","Spanish","Retailer","Brand"]},
{word:"Blazer", taboo:["Coat","Two-Piece","Gentleman","Jacket","Tuxedo"]},
{word:"Chanel", taboo:["Perfume","Ready-Made","Luxury","High-Fashion","French"]},
{word:"Phulkari", taboo:["Punjab","Floral","Embroidery","Culture","Weaving"]},
{word:"Handkerchief", taboo:["Cloth","Wipe","Dry","Pocket","Hankie"]},
{word:"Bowtie", taboo:["Formal","Collar","Shirt","Waiter","Necktie"]},
{word:"Ring", taboo:["Wedding","Diamond","Finger","Engagement","Occasion"]},
{word:"Sewing", taboo:["Stitching","Machine","Needle","Threads","Sweaters"]},
{word:"Gucci", taboo:["Italian","Fashion","Luxury","Leather","Florence"]},
{word:"Shoe", taboo:["Formal","Jogging","Walk","Socks","Footwear"]},
{word:"Trend", taboo:["Latest","Current","Present","Times","New"]},
{word:"Silhouette", taboo:["Overall","Line","Light","Shape","Dark"]},
{word:"Vogue", taboo:["Fashion","Magazine","Lifestyle","Beauty","Culture"]},
{word:"Seamstress", taboo:["Sewing","Weaving","Occupation","Person","Woman"]},
{word:"H&M", taboo:["Brand","Company","Clothing","Fashion","Retail"]},
{word:"Washable", taboo:["Machine","Handwash","Clothes","Feature","Water"]},
{word:"Retro", taboo:["Past","Olden","Earlier","Style","Historical"]},
{word:"Pattern", taboo:["Design","Repeated","Regularity","Predictable","Similarity"]},
{word:"Conditioner", taboo:["Shampoo","Haircare","Mosituriser","Shine","Damage"]},
{word:"Sherwani", taboo:["Jodhpuri","Coat","Achkan","Kurta","Bandhgala"]},
{word:"Trademark", taboo:["Symbol","Sign","Style","Signature","Expression"]},
{word:"Bespoke", taboo:["Customise","Customer","Specific","Particular","Commissioned"]},
{word:"Suspenders", taboo:["Strap","Pant","Scout","Buckles","Support"]},
{word:"Hoodie", taboo:["Sweatshirt","Jacket","Head","Cap","Cool"]},
{word:"Cosplay", taboo:["Comicon","Character","Dress","Costume","Clothes"]},
{word:"Crown", taboo:["King","Throne","Royal","Circular","Decoration"]},
{word:"Advertising", taboo:["Marketing ","Needs","Buy","Sponsored","Promote"]}
]
